from django.conf.urls import url, include
from django.contrib import admin
from . import views, views_extra

urlpatterns = [
    url(r'^$',views.ViewData.as_view(),
        name='applicantData'),
    url(r'^dateFormat/$',views.DateRefresh.as_view(),
        name='dateFormat'),
    url(r'^createcsv/$',views.CSVView.as_view(),
        name='createCSV'),
    url(r'^adminapplicationViews/(?P<id>\d+)/$', 
        views.ApplicationAdminView,
        name="admin-application-views"),
    url(r'^adminView.pdf/(?P<id>\d+)/$', 
        views.ApplicantAdmin.as_view(),
        name='adminView'),
    url(r'^userdatacsv/$', views.userdatacsv_view, 
        name="userdataCSV"),
    url(r'^usercsv/$', views.user_csv_view, 
        name='usercsv'),
	url(r'^userDateFormat/$',views.userDateRefresh,
        name='userDateFormat'),
	url(r'^userdataview/$',views.userdataView,
        name='userdataview'),
	url(r'^paymentData/$',
        views.paymentDataView,
        name='paymentData'),
    url(r'^createpaymentcsv/$',views.csv_payment_view,
        name='createpaymentCSV'),
    url(r'^date-refresh-payment/$',views.date_refresh_payment,
        name='dateFormat1'),
    url(r'^passport-photo-zip/$', views.zip_all_photo_file,
        name='passport_photo'),
    url(r'^application-status-report/$', views.application_status_report,
        name='application_status_report'),
    url(r'^ajax_data/(?P<pg>\d+)/(?P<st>[\w\-\s\.\,]+)/(?P<fm_dt>[\d\-\:\s]+)/(?P<to_dt>[\d\-\:\s]+)/(?P<pg_typ>[\w\-\s]+)/(?P<adm_bat>[\w\-\s]+)$',
     views.MyDataView.as_view(), name='table_data'),
    url(r'^usr_ajax_data/(?P<fm_dt>[\d\-\:\s]+)/(?P<to_dt>[\d\-\:\s]+)/$',
     views.UserDataView.as_view(), 
     name='usr_table_data'),
    url(r'^payment_ajax_data/(?P<fm_dt>[\d\-\:\s]+)/(?P<to_dt>[\d\-\:\s]+)/(?P<bank>[\w\-\s\.\,]+)/$',
     views.PaymentAppDataView.as_view(), 
     name='pay_app_table_data'),
    url(r'^app-archive-data/$', views_extra.app_archive_data, 
        name='app-archive-data'),
    url(r'^archive-progress$', views_extra.archive_progress,
        name="archive_progress"),
    url(r'^adm-man-id-gen/(?P<app_id>\d+)/$',views_extra.adm_manID_gen,
        name='adm_man_id_gen'),

    url(r'^name-change-list/$', views_extra.name_change_list,
      name='nc-list'),
    url(r'^name-change-form/(?P<application_id>\d+)/$', views_extra.name_change_form,
      name='nc-form'),
    url(r'^sdms-progress$', views_extra.sdms_progress,
        name="sdms_progress"),
    url(r'^ncl_ajax_data/(?P<pg>\d+)/(?P<ab>[\d\-\s]+)/(?P<p_type>[\w\-\s\.\,]+)/$',
     views_extra.NclDataView.as_view(), name='ncl-tab-data'),

    url(r'^sdms_error_download/error.txt$', views_extra.sdms_error_download,
      name='sdms-error-download'),

    url(r'^sync_student_list/sync_list.txt$', views_extra.sync_student_list,
      name='sync-student-list'),


    url(r'^dmr_report_specific/$',
      views_extra.DMR.as_view(),{'program_type': ['specific',],
      'title':'DMR - Program wise - Specific Programs'}, name='dmr-spec'), 

    url(r'^dmr_report_cluster/$',
      views_extra.DMR.as_view(),{'program_type': ['cluster',],
      'title':'DMR - Program wise - Cluster Programs'}, name='dmr-cluster'),

    url(r'^dmr_report_non_specific/$',
     views_extra.DMR.as_view(), {'program_type': ['non-specific',],
     'title':'DMR - Program wise - Non-Specific Programs'}, name='dmr-non-spec'),
    url(r'^dmr_daily__non_specific/$',
     views_extra.DMRNonSpecific.as_view(), name='dmr-daily-non-spec'),

    url(r'^fee-waiver-report/$', views_extra.WaiverReport.as_view(),
      name='waiver-report'),
    url(r'^fee-waiver-report-ajax/(?P<b_id>[\d\-\s]+)/$',
            views_extra.WaiverReportDataView.as_view(),
      name='waiver-report-ajax'),


    url(r'^milestone-report/$', views_extra.ApplicationMilestoneReport.as_view(),
      name='milestone-report'),
    url(r'^milestone-report-ajax/(?P<b_id>[\d\-\s]+)/(?P<p_id>[\d]+)/(?P<p_type>[\w\-\s\.\,]+)/$', views_extra.MilestoneView.as_view(),
      name='milestone-report-ajax'),

    url(r'^followup-mail-logs/$', views_extra.followup_mail_logs,
      name='followup-mail-logs'),
    url(r'^followup-mail-logs-ajax/(?P<fm_dt>[\d\-\:\s]+)/(?P<to_dt>[\d\-\:\s]+)/$',
      views_extra.FMLView.as_view(),name='followup-mail-logs-ajax'),


    url(r'^adm-regen-offer/(?P<ap_id>\d+)/$',
     views_extra.adm_regen_offer, name='adm_regen_offer'),

    url(r'^admin-offer-redirect/(?P<alert_status>\w+)/(?P<id>\d+)/$', 
        views.ApplicationAdminView,
        name="admin-offer-redirect"),
    
    #changes made by sai for Applicant Archieve Data
    url(r'^archive-data-view/$',views.ArchiveHomeDataView.as_view(),
        name='archive-data-view'),
    url(r'^ajax_archive_data/(?P<pg>\d+)/(?P<st>[\w\-\s\.\,]+)/(?P<fm_dt>[\d\-\:\s]+)/(?P<to_dt>[\d\-\:\s]+)/(?P<pg_typ>[\w\-\s]+)/(?P<adm_bat>[\w\-\s]+)$',
     views.ArchiveDataView.as_view(), name='table_archive_data'),
    url(r'^postArchApp/$',views.FilterArchivalApplicant.as_view(),
        name='postArchApp'),
    url(r'^adminapplicationarchiveViews/(?P<pk>\d+)/(?P<run_id>\d+)/$', 
        views.ApplicationAdminArchiveView.as_view(),
        name="admin-application-archive-views"),
    url(r'^createarchivecsv/$',views.CSVArchiveView.as_view(),
        name='createArchiveCSV'),

    url(r'^prog-change-report/$', views_extra.ProgramChangeReport.as_view(),
      name='prog-change-report'),
    url(r'^prog-change-report-ajax/(?P<b_id>[\d\-\s]+)/$',
        views_extra.ProgChangeReportAjax.as_view(),
        name='prog-change-report-ajax'),

  url(r'^prog-loc-report-cluster/$',
    views_extra.ProgramLocationReport.as_view(),
    {'program_type':['cluster',],'content_title':'Cluster'}, name='prog-loc-report-cluster'),
  url(r'^prog-loc-report-specific/$',
    views_extra.ProgramLocationReport.as_view(),
    {'program_type':['specific',],'content_title':'Specific'}, name='prog-loc-report-specific'),

  url(r'^student-course-report/$', views_extra.StudentCourseReport.as_view(),
      name='student-course-report'),
  url(r'^student-course-report-ajax/$', 
      views_extra.StudentCourseReportDataView.as_view(),
      name='student-course-report-ajax'),
   url(r'^pre_sel_rej_email/$',
        views_extra.SendPreConfirmSelRejEmail.as_view(),
        name="pre_sel_rej_email"),
   url(r'^dmr_daily__certification/$',
     views_extra.AdminDMRCertification.as_view(), name='dmr-daily-certification'),
   url(r'^dmr-daily-cluster/$',
     views_extra.AdminDMRCluster.as_view(), name='dmr-daily-cluster'),
   url(r'^dmr-daily-specific/$',
     views_extra.AdminDMRSpecific.as_view(), name='dmr-daily-specific'),
   # outbound inbound
  url(r'^inbound/$', views_extra.InboundView.as_view(), name='inbound'),
  url(r'^inbound_ajax/(?P<to_dt>[\d\-\:\s]+)/(?P<fm_dt>[\d\-\:\s]+)$',
     views_extra.InboundLogAjax.as_view(), name='inbound-ajax'),

  url(r'^outbound/$', views_extra.OutboundView.as_view(),name='outbound'),
  url(r'^outbound_ajax/(?P<to_dt>[\d\-\:\s]+)/(?P<fm_dt>[\d\-\:\s]+)$',
    views_extra.OutboundLogAjax.as_view(), name='outbound-ajax'),
]
