# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-03-22 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhoc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhoczestemitransaction',
            name='cancelled_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adhoczestemitransaction',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
