# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-08-26 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0115_auto_20190820_1325'),
        ('adhoc', '0004_auto_20190402_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdhocEduvanzApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('fee_type', models.CharField(max_length=45)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_terms_and_condition_accepted', models.BooleanField(default=False)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status_code', models.CharField(choices=[('New Loan Application', 'New Loan Application'), ('ELS101', 'Documents Pending'), ('ELS201', 'Under Approval'), ('ELS202', 'Approved'), ('ELS203', 'Processing Fee Paid'), ('ELS204', '1st EMI Paid'), ('ELS205', 'Both Processing Fee & 1st EMI Paid'), ('ELS206', 'Agreement Signed'), ('ELS301', 'Disbursed'), ('ELS401', 'Rejected'), ('ELS402', 'Dropped'), ('ELS102', 'Documents Pending'), ('FAILED', 'Failed to Process')], default='New Loan Application', max_length=25)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('approved_or_rejected_on', models.DateTimeField(blank=True, null=True)),
                ('lead_id', models.CharField(blank=True, max_length=25, null=True)),
                ('callback_meta', jsonfield.fields.JSONField(blank=True, null=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adhoceduvanzapplication_prog', to='registrations.Program')),
            ],
        ),
    ]
