# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-08-28 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('adhoc', '0005_adhoceduvanzapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhoceduvanzapplication',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='adhoceduvanzapplication',
            name='pin_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
