# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-08-28 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adhoc', '0006_auto_20190828_1649'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdhocMetaZest',
            new_name='AdhocMetaEmi',
        ),
    ]
