# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-06-27 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhoc', '0008_adhoceduvanzapplication_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhoczestemitransaction',
            name='zest_emi_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
