# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-07-20 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0127_auto_20200720_1356'),
        ('adhoc', '0009_adhoczestemitransaction_zest_emi_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdhocEzcredApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('fee_type', models.CharField(max_length=45)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('lead_id', models.CharField(blank=True, max_length=25, null=True)),
                ('lead_link', models.CharField(blank=True, max_length=100, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_terms_and_condition_accepted', models.BooleanField(default=False)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(default='New Loan Application', max_length=25)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('approved_or_rejected_on', models.DateTimeField(blank=True, null=True)),
                ('callback_meta', jsonfield.fields.JSONField(blank=True, null=True)),
                ('request_body_meta', jsonfield.fields.JSONField(blank=True, null=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adhocezcredapplication_prog', to='registrations.Program')),
            ],
        ),
    ]
