# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-01-12 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0140_auto_20210112_1316'),
        ('adhoc', '0011_auto_20210107_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdhocPropelldApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='New Loan Application', max_length=25)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('disbursed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('utr_number', models.CharField(blank=True, max_length=50, null=True)),
                ('request_body_meta', jsonfield.fields.JSONField(blank=True, null=True)),
                ('disbursement_date', models.DateTimeField(blank=True, null=True)),
                ('redirect_url', models.CharField(blank=True, max_length=300, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adhocpropelldapplication_app', to='registrations.StudentCandidateApplication')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adhocpropelldapplication_requests_created_6', to='registrations.Program')),
            ],
        ),
    ]
