# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-02-04 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adhoc', '0013_auto_20210127_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adhocpropelldapplication',
            name='application',
        ),
        migrations.AddField(
            model_name='adhocpropelldapplication',
            name='fee_type',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='adhocpropelldapplication',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
