# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-03-31 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adhoc', '0015_auto_20210210_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adhocpropelldapplication',
            old_name='request_body_meta',
            new_name='callback_body_meta',
        ),
    ]
