# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-07-25 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semester_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MetaZest',
            new_name='SemMetaZest',
        ),
        migrations.RenameModel(
            old_name='ZestEmiTransaction',
            new_name='SemZestEmiTransaction',
        ),
    ]
