# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-08-07 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('semester_api', '0003_auto_20181218_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemPaytmTransactions',
            fields=[
                ('order_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('student_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('request_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=30, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(blank=True, max_length=100, null=True)),
                ('gateway_name', models.CharField(blank=True, max_length=100, null=True)),
                ('merchant_id', models.CharField(blank=True, max_length=100, null=True)),
                ('response_message', models.TextField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('resp_json', jsonfield.fields.JSONField(blank=True, null=True)),
                ('redirect_url', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
