# Generated by Django 2.2.4 on 2019-08-23 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_batch_courseexamshedule_currentexam_datasynclogs_examattendance_examslot_examtype_examvenue_examvenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examvenue',
            name='pin_code',
            field=models.CharField(max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='should be a 6 digit integer', regex='^[1-9][0-9]{5}$')]),
        ),
    ]
