# Generated by Django 2.2.5 on 2019-09-06 05:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_auto_20190823_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseexamshedule',
            name='exam_type',
            field=models.ForeignKey(help_text='Only Active Exam Types Are Allowed To Be Chosen', on_delete=django.db.models.deletion.CASCADE, related_name='courseexamshedule_et', to='master.ExamType'),
        ),
        migrations.AlterField(
            model_name='courseexamshedule',
            name='semester',
            field=models.ForeignKey(blank=True, help_text='Only Semesters With Active Exam Entries Are Allowed', on_delete=django.db.models.deletion.CASCADE, related_name='courseexamshedule_sem', to='master.Semester'),
        ),
        migrations.AlterField(
            model_name='courseexamshedule',
            name='unit',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currentexam',
            name='hall_tkt_change_flag',
            field=models.BooleanField(default=False, help_text='If this is unchecked, modifications in hall ticket will not be allowed for students', verbose_name='Hall Ticket Changes Allowed?'),
        ),
        migrations.AlterField(
            model_name='currentexam',
            name='is_active',
            field=models.BooleanField(default=False, help_text='If the flag is unchecked, student will not be allowed to view and download hall tickets', verbose_name='Exam Active Flag'),
        ),
        migrations.AlterField(
            model_name='examvenue',
            name='pin_code',
            field=models.CharField(max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='should be a 6 digit integer', regex='^\\d{6}$')]),
        ),
        migrations.AlterUniqueTogether(
            name='courseexamshedule',
            unique_together={('course_code', 'exam_type', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='examtype',
            unique_together={('exam_type', 'evaluation_type')},
        ),
    ]
