# Generated by Django 2.2.5 on 2019-09-06 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_auto_20190906_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseexamshedule',
            name='batch',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='courseexamshedule_batch', to='master.Batch'),
        ),
    ]
