# Generated by Django 2.2.5 on 2019-09-12 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_auto_20190906_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentexam',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currentexam_sem', to='master.Semester'),
        ),
    ]
