# Generated by Django 2.2.5 on 2019-09-27 07:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_auto_20190924_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseexamshedule',
            name='course_code',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_course_code', message='Course code should not have spaces. Course code must be Alphanumeric', regex='^[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='examvenueslotmap',
            name='exam_venue',
            field=models.ForeignKey(help_text='Choose Location First. Only Active Venues will be listed', on_delete=django.db.models.deletion.CASCADE, related_name='examvenueslotmap_ev', to='master.ExamVenue'),
        ),
    ]
