# Generated by Django 2.2.5 on 2019-10-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0010_auto_20191017_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examattendance',
            name='attendance_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
