# Generated by Django 2.2.6 on 2019-10-29 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0011_auto_20191017_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='photo_path',
            new_name='photo',
        ),
    ]
