# Generated by Django 2.2.7 on 2019-11-05 13:17

from django.db import migrations
import easy_thumbnails.fields
import master.models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0012_auto_20191029_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, max_length=1000, null=True, upload_to=master.models.extract_photo_path, verbose_name='Photo Path'),
        ),
    ]
