# Generated by Django 2.2.7 on 2019-11-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0013_auto_20191105_1847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseexamshedule',
            options={'verbose_name': 'Course Exam Schedule'},
        ),
        migrations.AlterField(
            model_name='batch',
            name='application_center_batch',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='examvenue',
            name='venue_address',
            field=models.TextField(max_length=150),
        ),
    ]
