# Generated by Django 2.2.7 on 2019-11-14 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0014_auto_20191112_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examvenueslotmap',
            name='exam_venue',
            field=models.ForeignKey(help_text='Choose Location First. Only Active Venues will be listed', on_delete=django.db.models.deletion.CASCADE, related_name='examvenueslotmap_ev', to='master.ExamVenue', verbose_name='Venue Short Name'),
        ),
    ]
