# Generated by Django 2.2.7 on 2019-11-28 07:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0015_auto_20191114_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='course',
            field=models.CharField(default='default', max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_course_code', message='Course code should not have spaces. Course code must be Alphanumeric', regex='^[a-zA-Z0-9]+$')]),
        ),
    ]
