# Generated by Django 2.2.7 on 2019-11-28 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0016_auto_20191128_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentregistration',
            old_name='course',
            new_name='course_code',
        ),
        migrations.AlterUniqueTogether(
            name='studentregistration',
            unique_together={('course_code', 'student', 'semester')},
        ),
    ]
