# Generated by Django 2.2.7 on 2019-12-05 04:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0017_auto_20191128_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='course_code',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_course_code', message='Course code should not have spaces. Course code must be Alphanumeric', regex='^[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterUniqueTogether(
            name='currentexam',
            unique_together={('exam_type', 'program', 'semester', 'batch')},
        ),
    ]
