# Generated by Django 2.2.7 on 2019-12-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0018_auto_20191205_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='examvenue',
            name='student_count_limit',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
