# Generated by Django 2.2.7 on 2019-12-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0019_examvenue_student_count_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='examvenueslotmap',
            name='student_count_limit',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
