# Generated by Django 2.2.7 on 2019-12-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0021_auto_20191218_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseexamshedule',
            name='exam_venue_slot_maps',
            field=models.ManyToManyField(blank=True, to='master.ExamVenueSlotMap'),
        ),
    ]
