# Generated by Django 2.2.7 on 2020-03-09 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0023_auto_20200210_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseexamshedule',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseexamshedule_batch', to='master.Batch'),
        ),
        migrations.AlterField(
            model_name='courseexamshedule',
            name='semester',
            field=models.ForeignKey(help_text='Only Semesters With Active Exam Entries Are Allowed', on_delete=django.db.models.deletion.CASCADE, related_name='courseexamshedule_sem', to='master.Semester'),
        ),
        migrations.AlterUniqueTogether(
            name='courseexamshedule',
            unique_together={('course_code', 'exam_type', 'semester', 'batch')},
        ),
    ]
