# Generated by Django 2.2.7 on 2020-10-08 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0024_auto_20200309_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineExamAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=12)),
                ('course_code', models.CharField(max_length=15)),
                ('makeup_allowed', models.BooleanField(default=False)),
                ('course_name', models.CharField(blank=True, max_length=50, null=True)),
                ('exam_date', models.DateTimeField(blank=True, null=True)),
                ('total_questions', models.IntegerField(blank=True, null=True)),
                ('total_attempted', models.IntegerField(blank=True, null=True)),
                ('total_blank', models.IntegerField(blank=True, null=True)),
                ('image_uploaded', models.IntegerField(blank=True, null=True)),
                ('test_start_time', models.CharField(blank=True, max_length=45, null=True)),
                ('test_end_time', models.CharField(blank=True, max_length=45, null=True)),
                ('submission_type', models.CharField(blank=True, max_length=20, null=True)),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onlineexamattendance_oea', to='master.ExamType')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onlineexamattendance_sem', to='master.Semester')),
            ],
        ),
    ]
