# Generated by Django 2.2.7 on 2020-11-03 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0026_examvenuelock'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentexam',
            name='missing_tkt_exception_flag',
            field=models.BooleanField(default=False, help_text='Checking this checkbox will enable student who haven’t generated their hall ticket yet to generate the same even after the hall ticket change window is closed', verbose_name='Allow Hall Ticket Generation for Students without Hall Tickets during Freeze Window'),
        ),
        migrations.CreateModel(
            name='HallTicketException',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=12)),
                ('exception_end_date', models.DateField(blank=True, null=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hallticketexception_sem', to='master.Semester', verbose_name='Semester Name')),
            ],
        ),
    ]
