# Generated by Django 2.2.7 on 2020-12-03 06:06

from django.db import migrations, models
import master.models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0027_auto_20201103_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadStudentPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=12)),
                ('student_photo', models.ImageField(upload_to=master.models.path_and_rename)),
            ],
        ),
    ]
