# Generated by Django 2.2.7 on 2021-02-09 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0028_uploadstudentphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='examslot',
            name='slot_start_time',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Slot Exam Start Time'),
        ),
    ]
