# Generated by Django 2.2.7 on 2021-03-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0029_examslot_slot_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='personal_email',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='personal_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
