# Generated by Django 2.2.7 on 2021-03-18 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0030_auto_20210303_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallticketexception',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hallticketexception_sem', to='master.Semester', verbose_name='Semester Name'),
        ),
    ]
