# Generated by Django 2.2.7 on 2021-03-18 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0031_auto_20210318_1638'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hallticketexception',
            unique_together={('student_id', 'semester')},
        ),
    ]
