# Generated by Django 2.2.7 on 2021-03-30 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0032_auto_20210318_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineexamattendance',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onlineexamattendance_sem', to='master.Semester'),
        ),
        migrations.AlterUniqueTogether(
            name='onlineexamattendance',
            unique_together={('student_id', 'exam_type', 'course_code', 'semester')},
        ),
    ]
