# Generated by Django 2.2.7 on 2021-04-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0033_auto_20210330_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentexam',
            name='exm_slot_an',
            field=models.CharField(blank=True, default='', max_length=75, verbose_name='Exam Slot Time Text (Afternoon)'),
        ),
        migrations.AddField(
            model_name='currentexam',
            name='exm_slot_fn',
            field=models.CharField(blank=True, default='', max_length=75, verbose_name='Exam Slot Time Text (Forenoon)'),
        ),
    ]
