# Generated by Django 2.2.7 on 2021-04-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0034_auto_20210419_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentexam',
            name='hall_tkt_template',
            field=models.CharField(blank=True, choices=[('hall_ticket.html', 'Std Hall Tkt Template')], max_length=45, null=True, verbose_name='Choose Hall Ticket template'),
        ),
    ]
