"""
Django settings for ema project.

Generated by 'django-admin startproject' using Django 2.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'i)i%egokb8-6bebrx(xqaiyv90inc3d43lqe)+_j9y1qx68pt2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['exam-mgmt.bits-pilani.ac.in','127.0.0.1']
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
TEMPLATE_DEBUG = DEBUG
SESSION_EXPIRE_AT_BROWSER_CLOSE = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_results',
    'rest_framework',
]

THIRD_PARTY_APP = [
    'djangoformsetjs',
    'django_extensions',
    'bootstrap3',
    'django_mysql',
    'table',
    'widget_tweaks',
    'import_export',
    'bootstrap_datepicker_plus',
    'easy_pdf',
    'easy_thumbnails',
]

BITS_APP = [
    'master',
    'administrator',
    'coordinator',
    'student',
    #'sso_login',
    'shibboleth',
]

INSTALLED_APPS += THIRD_PARTY_APP + BITS_APP

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'shibboleth.middleware.ShibbolethRemoteUserMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ema.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shibboleth.context_processors.login_link',
                'shibboleth.context_processors.logout_link',
            ],
        },
    },
]

WSGI_APPLICATION = 'ema.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
	'default': {
	'ENGINE': 'django.db.backends.mysql',
	'NAME': 'ema',
	'USER': 'admin',
	'PASSWORD': r'B!T$PPilani9*',
	'HOST': 'bitsdb.cosqzd7ygxjn.ap-south-1.rds.amazonaws.com',
	'PORT': '3306',
	}
}
# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

from pytz import timezone as indiantime
INDIAN_TIME_ZONE = indiantime('Asia/Kolkata')
TIME_ZONE = INDIAN_TIME_ZONE.zone

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

DEFAULT_FILE_STORAGE = 'ema.storage.MediaStorage'

AWS_ACCESS_KEY_ID = 'AKIAI2VBEJAEPIDKWYFQ'
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'ema-bucket-prod'
AWS_QUERYSTRING_AUTH = False
S3_USE_SIGV4 = True
AWS_REGION_NAME = 'ap-south-1'
S3_MEDIA_DIR = 'media'
AWS_S3_STORAGE = 's3'
S3_URL = '{0}.s3.ap-south-1.amazonaws.com'.format(AWS_STORAGE_BUCKET_NAME)

MEDIA_URL = 'https://{0}/{1}/'.format(S3_URL, 'media')
STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(os.environ['HOME'], 'ema-share-dir', 'ema','media')
STATIC_ROOT = os.path.join(os.environ['HOME'], 'ema-share-dir', 'ema','static')
STATICFILES_DIRS = (os.path.join(BASE_DIR, "ema", "static"), )

#bits mail settings
EMAIL_USE_TLS = True

EMAIL_HOST = 'smtp-wilp.bits-pilani.ac.in'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'ema-2021-03-01@wilp.bits-pilani.ac.in'
EMAIL_HOST_PASSWORD = '65ee4d69-b963-460e-b512-f87d370bb638'
FROM_EMAIL = 'noreply@wilp.bits-pilani.ac.in'

# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_HOST_USER = 'noreply@wilp.bits-pilani.ac.in'
# EMAIL_HOST_PASSWORD = '-40Joules'
# FROM_EMAIL = 'noreply@wilp.bits-pilani.ac.in'

DEFAULT_FROM_EMAIL = FROM_EMAIL
SERVER_EMAIL = EMAIL_HOST_USER

#Shibboleth
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'ema.backends.ShibbolethRemoteUserBackend',
)

SHIBBOLETH_ATTRIBUTE_MAP = {
    'HTTP_PROXY_CNAME': (True, 'username'),
    'HTTP_PROXY_USER': (True, 'email'),
    'HTTP_PROXY_ROLE': (True, 'role'),
}
LOGIN_URL = '/Shibboleth.sso/Login'
SHIBBOLETH_LOGOUT_URL = '/Shibboleth.sso/Logout'
SHIBBOLETH_LOGOUT_REDIRECT_URL = 'https://elearn.bits-pilani.ac.in/user/'
SESSION_EXPIRE_AT_BROWSER_CLOSE = True 


BOOTSTRAP3 = {
    'include_jquery': True,
}


BITS_EMAIL_DOMAIN = r'.*\.bits-pilani.ac.in$'

AC_DOMAIN = 'wilpadmissions.bits-pilani.ac.in'


THUMBNAIL_ALIASES = {
    '': {
        'avatar': {'size': (300, 300)},
        'year_thumb': {
            'size': (300, 100),
            'autocrop': True,
            'crop': 'smart',
            'upscale': True,
        },
        'zip_thumb': {
            'size': (150, 150),
            'autocrop': True,
            'crop': 'smart',
            'upscale': True,
        },
    },
}

AC_DOMAIN = 'https://wilpadmissions.bits-pilani.ac.in/'

SDMS_API_URL = "https://sdms.bits-pilani.ac.in/api/v1/student_data/"
SDMS_API_AUTHKEY = "e71b91c9-0904-4025-9bf0-722ccd16ace3"
SDMS_API_AUTHHEADER = "AuthToken"
SDMS_STUDENT_URL = "https://sdms.bits-pilani.ac.in/profile/"

ELEARN_API_URL = " https://elearn.bits-pilani.ac.in/user/programmelist/"
ELEARN_API_AUTHKEY = "420fef54-ff26-4679-a3e6-08de0a9d263d"
ELEARN_API_AUTHHEADER = "AUTH"

CELERY_RESULT_BACKEND = 'django-db'

CELERY_BROKER_URL = 'redis://localhost:6379/0'

CELERY_TIMEZONE = indiantime('Asia/Kolkata').zone
CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']
CELERY_TASK_SERIALIZER = 'pickle'
CELERY_RESULT_SERIALIZER = 'pickle'
CELERY_IMPORTS=("master.tasks")
QPM_HOST_URL = "https://qpm-wilp.bits-pilani.ac.in"


ENABLE_FACE_DETECTION = True
