# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-04-06 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaAdhocPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_url_requested_on', models.DateTimeField(blank=True, null=True)),
                ('payment_url_requested_data', jsonfield.fields.JSONField(blank=True, null=True)),
                ('payment_url_response_data', jsonfield.fields.JSONField(blank=True, null=True)),
                ('payment_done_responded_on', models.DateTimeField(blank=True, null=True)),
                ('payment_done_url_requested_data', jsonfield.fields.JSONField(blank=True, null=True)),
                ('payment_done_url_response_data', jsonfield.fields.JSONField(blank=True, null=True)),
                ('fee_type', models.CharField(max_length=100)),
                ('sequence_number', models.IntegerField()),
            ],
        ),
    ]
