# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-04-06 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaadhocpayment',
            name='email',
            field=models.EmailField(default='a', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
