# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-04-16 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits_rest', '0002_metaadhocpayment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaadhocpayment',
            name='adhoc_error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
