# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-23 18:58
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bits_rest', '0006_auto_20180621_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='zestemitransaction',
            name='req_json_data',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
