# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-26 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits_rest', '0007_zestemitransaction_req_json_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='zestemitransaction',
            name='status',
            field=models.CharField(blank=True, choices=[(None, 'No status'), ('RiskApproved', 'RiskApproved'), ('OutOfStock', 'OutOfStock'), ('BankAccountDetailsComplete', 'BankAccountDetailsComplete'), ('ApplicationInProgress', 'ApplicationInProgress'), ('CustomerCancelled', 'CustomerCancelled'), ('InArrears', 'InArrears'), ('WrittenOff', 'WrittenOff'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled'), ('Approved', 'Approved'), ('Referred', 'Referred'), ('DocumentsComplete', 'DocumentsComplete'), ('DepositPaid', 'DepositPaid'), ('LoanAgreementAccepted', 'LoanAgreementAccepted'), ('Declined', 'Declined'), ('PreAccepted', 'PreAccepted'), ('TimeoutCancelled', 'TimeoutCancelled'), ('MerchantCancelled', 'MerchantCancelled'), ('RiskPending', 'RiskPending')], max_length=50, null=True),
        ),
    ]
