# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-28 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0085_auto_20180625_1324'),
        ('bits_rest', '0011_auto_20180627_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaZest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('errors', jsonfield.fields.JSONField(blank=True, null=True)),
                ('created_on_datetime', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metazest_1', to='registrations.StudentCandidateApplication')),
            ],
        ),
    ]
