# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-28 14:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bits_rest', '0012_metazest'),
    ]

    operations = [
        migrations.AddField(
            model_name='metazest',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='metazest_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metazest',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metazest_1', to='registrations.StudentCandidateApplication'),
        ),
    ]
