# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-28 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bits_rest', '0013_auto_20180628_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metazest',
            name='application',
        ),
    ]
