# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-05-30 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('bits_rest', '0016_auto_20181022_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45, unique=True)),
                ('password', models.TextField()),
                ('token', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InBoundCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=45)),
                ('called_on', models.DateTimeField()),
                ('customer_name', models.CharField(max_length=45)),
                ('comment', models.TextField(blank=True, null=True)),
                ('cust_email', models.EmailField(max_length=254)),
                ('city', models.CharField(blank=True, max_length=45, null=True)),
                ('emi_enquiry_flag', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InBoundPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('bound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inboundphone_bound', to='bits_rest.InBoundCall')),
            ],
        ),
        migrations.CreateModel(
            name='InBoundProgramInterested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=60)),
                ('bound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inboundprograminterested_bound', to='bits_rest.InBoundCall')),
            ],
        ),
        migrations.CreateModel(
            name='InBoundQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('bound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inboundquery_bound', to='bits_rest.InBoundCall')),
            ],
        ),
        migrations.CreateModel(
            name='InBoundVOC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('bound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inboundvoc_bound', to='bits_rest.InBoundCall')),
            ],
        ),
        migrations.CreateModel(
            name='OutBoundCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=45)),
                ('called_on', models.DateTimeField()),
                ('desposition', models.CharField(max_length=45)),
                ('customer_name', models.CharField(max_length=45)),
                ('cust_email', models.EmailField(max_length=254)),
                ('current_status', models.CharField(max_length=45)),
                ('call_response', models.CharField(max_length=45)),
                ('dialer_status', models.CharField(max_length=45)),
                ('comment', models.TextField(blank=True, null=True)),
                ('emi_enquiry_flag', models.BooleanField(default=False)),
                ('call_type', models.CharField(blank=True, max_length=45, null=True)),
                ('city', models.CharField(blank=True, max_length=45, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutBoundPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('bound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outboundphone_bound', to='bits_rest.OutBoundCall')),
            ],
        ),
        migrations.CreateModel(
            name='OutBoundProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=60)),
                ('bound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outboundprogram_bound', to='bits_rest.OutBoundCall')),
            ],
        ),
        migrations.CreateModel(
            name='OutBoundProgramInterested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=60)),
                ('bound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outboundprograminterested_bound', to='bits_rest.OutBoundCall')),
            ],
        ),
        migrations.CreateModel(
            name='OutBoundQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('bound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outboundquery_bound', to='bits_rest.OutBoundCall')),
            ],
        ),
        migrations.CreateModel(
            name='OutBoundVOC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('bound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outboundvoc_bound', to='bits_rest.OutBoundCall')),
            ],
        ),
    ]
