# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-08-09 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0111_auto_20190808_2003'),
        ('bits_rest', '0016_auto_20181022_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='EduvanzApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=32, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_terms_and_condition_accepted', models.BooleanField(default=False)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(default='Initiated', max_length=25)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('approved_on', models.DateTimeField(blank=True, null=True)),
                ('lead', models.CharField(blank=True, max_length=25, null=True)),
                ('meta_data', jsonfield.fields.JSONField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eduvanzapplication_app', to='registrations.StudentCandidateApplication')),
            ],
        ),
        migrations.CreateModel(
            name='PaytmHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORDERID', models.CharField(max_length=30, verbose_name='ORDER ID')),
                ('TXNDATE', models.DateTimeField(default=django.utils.timezone.now, verbose_name='TXN DATE')),
                ('TXNID', models.IntegerField(verbose_name='TXN ID')),
                ('BANKTXNID', models.IntegerField(blank=True, null=True, verbose_name='BANK TXN ID')),
                ('BANKNAME', models.CharField(blank=True, max_length=50, null=True, verbose_name='BANK NAME')),
                ('RESPCODE', models.IntegerField(verbose_name='RESP CODE')),
                ('PAYMENTMODE', models.CharField(blank=True, max_length=10, null=True, verbose_name='PAYMENT MODE')),
                ('CURRENCY', models.CharField(blank=True, max_length=4, null=True, verbose_name='CURRENCY')),
                ('GATEWAYNAME', models.CharField(blank=True, max_length=30, null=True, verbose_name='GATEWAY NAME')),
                ('MID', models.CharField(max_length=40)),
                ('RESPMSG', models.TextField(max_length=250, verbose_name='RESP MSG')),
                ('TXNAMOUNT', models.FloatField(verbose_name='TXN AMOUNT')),
                ('STATUS', models.CharField(max_length=12, verbose_name='STATUS')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paytmhistory_app', to='registrations.StudentCandidateApplication')),
            ],
        ),
    ]
