# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-05-30 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits_rest', '0017_agent_inboundcall_inboundphone_inboundprograminterested_inboundquery_inboundvoc_outboundcall_outboun'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundphone',
            name='data_type',
            field=models.CharField(default='main', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inboundprograminterested',
            name='data_type',
            field=models.CharField(default='main', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inboundquery',
            name='data_type',
            field=models.CharField(default='main', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inboundvoc',
            name='data_type',
            field=models.CharField(default='main', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outboundphone',
            name='data_type',
            field=models.CharField(default='main', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outboundprogram',
            name='data_type',
            field=models.CharField(default='main', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outboundprograminterested',
            name='data_type',
            field=models.CharField(default='main', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outboundquery',
            name='data_type',
            field=models.CharField(default='main', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outboundvoc',
            name='data_type',
            field=models.CharField(default='main', max_length=60),
            preserve_default=False,
        ),
    ]
