# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-08-13 07:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bits_rest', '0018_auto_20190809_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eduvanzapplication',
            old_name='meta_data',
            new_name='callback_meta',
        ),
        migrations.RenameField(
            model_name='eduvanzapplication',
            old_name='lead',
            new_name='lead_id',
        ),
    ]
