# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-05-31 07:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bits_rest', '0018_auto_20190530_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='last_updated_on',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2019, 5, 31, 7, 56, 18, 308524, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='timeout',
            field=models.DurationField(default=datetime.timedelta(0, 600)),
        ),
    ]
