# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-05-31 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits_rest', '0019_auto_20190531_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
