# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-05-31 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits_rest', '0020_auto_20190531_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='token',
        ),
        migrations.AddField(
            model_name='agent',
            name='key',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
