# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-06-04 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bits_rest', '0021_auto_20190531_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboundprogram',
            name='bound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outboundprogram_bound', to='bits_rest.OutBoundCall', unique=True),
        ),
    ]
