# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-06-04 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits_rest', '0022_auto_20190604_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outboundprogram',
            name='bound',
        ),
        migrations.AddField(
            model_name='outboundcall',
            name='program',
            field=models.CharField(default='hb01', max_length=60),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OutBoundProgram',
        ),
    ]
