# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-06-14 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0108_candidateselection_offer_letter'),
        ('bits_rest', '0024_auto_20190611_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inboundcall',
            name='application',
        ),
        migrations.AddField(
            model_name='inboundcall',
            name='application',
            field=models.ManyToManyField(to='registrations.StudentCandidateApplication'),
        ),
        migrations.RemoveField(
            model_name='outboundcall',
            name='application',
        ),
        migrations.AddField(
            model_name='outboundcall',
            name='application',
            field=models.ManyToManyField(to='registrations.StudentCandidateApplication'),
        ),
    ]
