# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-07-03 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits_rest', '0025_auto_20190614_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboundcall',
            name='application',
            field=models.ManyToManyField(blank=True, to='registrations.StudentCandidateApplication'),
        ),
        migrations.AlterField(
            model_name='outboundcall',
            name='application',
            field=models.ManyToManyField(blank=True, to='registrations.StudentCandidateApplication'),
        ),
    ]
