# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-08-19 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bits_rest', '0019_auto_20190813_1251'),
        ('bits_rest', '0026_auto_20190703_1249'),
    ]

    operations = [
    ]
