# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-08-20 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits_rest', '0027_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduvanzapplication',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
