# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-08-22 07:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bits_rest', '0028_auto_20190820_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eduvanzapplication',
            old_name='status',
            new_name='status_code',
        ),
    ]
