# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-08-28 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits_rest', '0030_auto_20190826_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduvanzapplication',
            name='status_code',
            field=models.CharField(choices=[(None, '-'), ('New Loan Application', 'New Loan Application'), ('ELS101', 'Documents Pending'), ('ELS201', 'Under Approval'), ('ELS202', 'Approved'), ('ELS203', 'Processing Fee Paid'), ('ELS204', '1st EMI Paid'), ('ELS205', 'Both Processing Fee & 1st EMI Paid'), ('ELS206', 'Agreement Signed'), ('ELS301', 'Disbursed'), ('ELS401', 'Rejected'), ('ELS402', 'Dropped'), ('ELS102', 'Documents Pending'), ('FAILED', 'Failed to Process')], default='New Loan Application', max_length=25),
        ),
    ]
