# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-10-31 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits_rest', '0031_auto_20190828_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paytmhistory',
            name='BANKTXNID',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='BANK TXN ID'),
        ),
        migrations.AlterField(
            model_name='paytmhistory',
            name='CURRENCY',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CURRENCY'),
        ),
        migrations.AlterField(
            model_name='paytmhistory',
            name='MID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paytmhistory',
            name='RESPCODE',
            field=models.CharField(max_length=100, verbose_name='RESP CODE'),
        ),
        migrations.AlterField(
            model_name='paytmhistory',
            name='TXNAMOUNT',
            field=models.CharField(max_length=100, verbose_name='TXN AMOUNT'),
        ),
        migrations.AlterField(
            model_name='paytmhistory',
            name='TXNID',
            field=models.CharField(max_length=100, verbose_name='TXN ID'),
        ),
    ]
