# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-05-28 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0126_auto_20200528_2101'),
        ('bits_rest', '0032_auto_20191031_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='EzcredApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('lead_id', models.CharField(blank=True, max_length=25, null=True)),
                ('lead_link', models.CharField(blank=True, max_length=100, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_terms_and_condition_accepted', models.BooleanField(default=False)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(default='New Loan Application', max_length=25)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('approved_or_rejected_on', models.DateTimeField(blank=True, null=True)),
                ('callback_meta', jsonfield.fields.JSONField(blank=True, null=True)),
                ('request_body_meta', jsonfield.fields.JSONField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ezcredapplication_app', to='registrations.StudentCandidateApplication')),
            ],
        ),
        migrations.CreateModel(
            name='EzcredApplicationcanceledloans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('lead_id', models.CharField(blank=True, max_length=25, null=True)),
                ('lead_link', models.CharField(blank=True, max_length=100, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_terms_and_condition_accepted', models.BooleanField(default=False)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(max_length=25)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('approved_or_rejected_on', models.DateTimeField(blank=True, null=True)),
                ('callback_meta', jsonfield.fields.JSONField(blank=True, null=True)),
                ('request_body_meta', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetaEzcredexceptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('errors', jsonfield.fields.JSONField(blank=True, null=True)),
                ('created_on_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
