# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-06-25 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits_rest', '0033_ezcredapplication_ezcredapplicationcanceledloans_metaezcredexceptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='zestemitransaction',
            name='zest_emi_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
