# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-08-19 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits_rest', '0034_zestemitransaction_zest_emi_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paytmhistory',
            name='ORDERID',
            field=models.CharField(max_length=100, verbose_name='ORDER ID'),
        ),
    ]
