# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-08-05 10:00
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bits_rest', '0040_auto_20210331_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='zestemitransaction',
            name='callback_meta',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
