# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_auto_20160621_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcandidateapplication',
            name='parallel_studies_flag',
            field=models.CharField(choices=[(None, 'Choose'), ('1', 'YES'), ('2', 'NO')], max_length=45),
        ),
    ]
