# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-29 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_auto_20160621_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationdocument',
            options={'ordering': ['document__mandatory_document']},
        ),
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ['mandatory_document']},
        ),
        migrations.AlterField(
            model_name='studentcandidateapplication',
            name='current_employment_status',
            field=models.CharField(choices=[(None, 'Choose Employment Status'), ('1', 'Employed'), ('3', 'Self Employed'), ('2', 'Unemployed')], max_length=20),
        ),
    ]
