# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-08 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_auto_20160629_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcandidateapplication',
            name='state',
            field=models.CharField(choices=[(None, 'Choose State(India)'), ('1', 'Andhra Pradesh'), ('2', 'Arunachal Pradesh'), ('3', 'Assam'), ('4', 'Bihar'), ('5', 'Chhattisgarh'), ('31', 'Delhi'), ('6', 'Goa'), ('7', 'Gujarat'), ('8', 'Haryana'), ('9', 'Himachal Pradesh'), ('10', 'Jammu & Kashmir'), ('11', 'Jharkhand'), ('12', 'Karnataka'), ('13', 'Kerala'), ('14', 'Madhya Pradesh'), ('15', 'Maharashtra'), ('16', 'Manipur'), ('17', 'Meghalaya'), ('18', 'Mizoram'), ('19', 'Nagaland'), ('20', 'Odisha (Orissa)'), ('30', 'Out Side India'), ('21', 'Punjab'), ('22', 'Rajasthan'), ('23', 'Sikkim'), ('24', 'Tamil Nadu'), ('25', 'Telangana'), ('26', 'Tripura'), ('27', 'Uttar Pradesh'), ('28', 'Uttarakhand'), ('29', 'West Bengal')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='applicationdocument',
            unique_together=set([('document', 'application')]),
        ),
    ]
