# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-04 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0007_auto_20160729_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
