# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-09 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0008_auto_20160804_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramLocationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_payment_deadline_date', models.DateTimeField()),
                ('orientation_date', models.DateTimeField()),
                ('lecture_start_date', models.DateTimeField()),
                ('orientation_venue', models.CharField(max_length=100)),
                ('lecture_venue', models.CharField(max_length=100)),
                ('admin_contact_person', models.CharField(max_length=50)),
                ('acad_contact_person', models.CharField(max_length=50)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programlocationdetails_requests_created_13459', to='registrations.Location')),
            ],
            options={
                'verbose_name': 'Program and Location Details',
                'verbose_name_plural': 'Program and Location Details',
            },
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='exception_notes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationpayment',
            name='fee_type',
            field=models.CharField(choices=[(None, 'Choose Fee Type'), ('1', 'Admission Fee'), ('2', 'Application Fee')], default='2', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicationpayment',
            name='payment_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AddField(
            model_name='programlocationdetails',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programlocationdetails_requests_created_8888', to='registrations.Program'),
        ),
        migrations.AlterUniqueTogether(
            name='programlocationdetails',
            unique_together=set([('program', 'location')]),
        ),
    ]
