# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-22 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0009_auto_20160809_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='programlocationdetails',
            name='acad_contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='eg +918326974266', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='programlocationdetails',
            name='admin_contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='eg +918326974266', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='programlocationdetails',
            name='acad_contact_person',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='programlocationdetails',
            name='admin_contact_person',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='programlocationdetails',
            name='lecture_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programlocationdetails',
            name='lecture_venue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='programlocationdetails',
            name='orientation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programlocationdetails',
            name='orientation_venue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
