# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-26 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0010_auto_20160822_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceptionlistorgapplicants',
            name='employee_email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='exceptionlistorgapplicants',
            name='exception_type',
            field=models.CharField(choices=[(None, 'FEE TYPE'), ('1', 'APPLICATION FEE'), ('2', 'ADMISSION FEE')], max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='exceptionlistorgapplicants',
            unique_together=set([('employee_email', 'exception_type')]),
        ),
    ]
