# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-31 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0011_auto_20160826_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_pay_req_date', models.DateTimeField(blank=True, null=True)),
                ('req_pay_status', models.IntegerField(blank=True, null=True)),
                ('req_json_data', jsonfield.fields.JSONField(blank=True, null=True)),
                ('req_json_return_data', jsonfield.fields.JSONField(blank=True, null=True)),
                ('req_pay_res_date', models.DateTimeField(blank=True, null=True)),
                ('res_pay_req_date', models.DateTimeField(blank=True, null=True)),
                ('res_pay_status', models.IntegerField(blank=True, null=True)),
                ('res_json_data', jsonfield.fields.JSONField(blank=True, null=True)),
                ('res_json_return_data', jsonfield.fields.JSONField(blank=True, null=True)),
                ('res_pay_res_date', models.DateTimeField(blank=True, null=True)),
                ('fee_type', models.CharField(choices=[(None, 'Choose Fee Type'), ('1', 'Admission Fee'), ('2', 'Application Fee')], max_length=16)),
                ('sequence_number', models.IntegerField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metapayment_requests_created_9830', to='registrations.StudentCandidateApplication')),
            ],
        ),
    ]
