# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-12 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import registrations.models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0012_metapayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormFieldPopulationSpecific',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=45)),
                ('show_on_form', models.BooleanField(default=True)),
                ('default_value', models.CharField(blank=True, max_length=45, null=True)),
                ('is_editable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramDocumentMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandatory_flag', models.BooleanField(default=False)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programdocumentmap_requests_created_2', to='registrations.DocumentType')),
            ],
            options={
                'ordering': ['mandatory_flag'],
            },
        ),
        migrations.CreateModel(
            name='ProgramDomainMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_domain', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.EmailField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCandidateApplicationSpecific',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registrations.StudentCandidateApplication')),
                ('collaborating_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentcandidateapplicationspecific_requests_created_1', to='registrations.CollaboratingOrganization')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='application_pdf_template',
            field=models.CharField(blank=True, choices=[(None, 'Choose'), ('app_pdf/oracle-pdf.html', 'Oracle')], max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='collaborating_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_requests_created_4', to='registrations.CollaboratingOrganization'),
        ),
        migrations.AddField(
            model_name='program',
            name='document_upload_page_path',
            field=models.CharField(blank=True, choices=[(None, 'Choose Document To Upload'), ('guidelines_document/oracle.html', 'Oracle')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='offer_letter_template',
            field=models.CharField(blank=True, choices=[(None, 'Choose')], max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='org_logo_image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=registrations.models.document_upload_page_path),
        ),
        migrations.AddField(
            model_name='programdomainmapping',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programdomainmapping_requests_created_1', to='registrations.Program'),
        ),
        migrations.AddField(
            model_name='programdocumentmap',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programdocumentmap_requests_created_1', to='registrations.Program'),
        ),
        migrations.AddField(
            model_name='formfieldpopulationspecific',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formfieldpopulationspecific_requests_created_1', to='registrations.Program'),
        ),
        migrations.AlterUniqueTogether(
            name='programdocumentmap',
            unique_together=set([('program', 'document_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='formfieldpopulationspecific',
            unique_together=set([('program', 'field_name')]),
        ),
    ]
