# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-25 08:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0013_auto_20160912_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstSemCourseList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admit_batch', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('course_id', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=60)),
                ('course_unit', models.PositiveIntegerField()),
                ('active_flag', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Course List',
                'verbose_name_plural': 'Course List',
            },
        ),
        migrations.CreateModel(
            name='ProgramQualificationRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Program Qualification Category Mapping',
                'verbose_name_plural': 'Program Qualification Category Mapping',
            },
        ),
        migrations.CreateModel(
            name='QualificationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'ordering': ['category_name'],
                'verbose_name': 'Qualification Category',
                'verbose_name_plural': 'Qualification Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['serial_number_on_page']},
        ),
        migrations.RemoveField(
            model_name='program',
            name='specific_non_specific',
        ),
        migrations.AddField(
            model_name='program',
            name='active_for_applicaton_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='program',
            name='mentor_id_req',
            field=models.BooleanField(default=True, verbose_name='Mentor Consent Required'),
        ),
        migrations.AddField(
            model_name='program',
            name='min_work_exp_in_months',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Minimum Work Experience in Months'),
        ),
        migrations.AddField(
            model_name='program',
            name='program_type',
            field=models.CharField(choices=[(None, 'Choose Program Type'), ('specific', 'SPECIFIC'), ('non-specific', 'NON-SPECIFIC'), ('cluster', 'CLUSTER'), ('others', 'OTHERS')], default='non-specific', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='serial_number_on_page',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='show_on_page_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='program',
            name='show_to_fee_wvr_appl_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='program',
            name='work_exp_check_req',
            field=models.BooleanField(default=True, verbose_name='Work Experience Check Required'),
        ),
        migrations.AlterField(
            model_name='candidateselection',
            name='student_id',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='offer_letter_template',
            field=models.CharField(blank=True, choices=[(None, 'Choose'), ('offer_pdf/oracle.html', 'oracle')], max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='studentcandidateapplication',
            name='state',
            field=models.CharField(choices=[(None, 'Choose State(India)'), ('1', 'Andhra Pradesh'), ('35', 'Andaman and Nicobar Islands'), ('2', 'Arunachal Pradesh'), ('3', 'Assam'), ('4', 'Bihar'), ('34', 'Chandigarh'), ('5', 'Chhattisgarh'), ('33', 'Dadra and Nagar Haveli'), ('32', 'Daman and Diu'), ('31', 'Delhi'), ('6', 'Goa'), ('7', 'Gujarat'), ('8', 'Haryana'), ('9', 'Himachal Pradesh'), ('10', 'Jammu & Kashmir'), ('11', 'Jharkhand'), ('12', 'Karnataka'), ('13', 'Kerala'), ('36', 'Lakshadweep'), ('14', 'Madhya Pradesh'), ('15', 'Maharashtra'), ('16', 'Manipur'), ('17', 'Meghalaya'), ('18', 'Mizoram'), ('19', 'Nagaland'), ('20', 'Odisha (Orissa)'), ('30', 'Out Side India'), ('37', 'Pondicherry'), ('21', 'Punjab'), ('22', 'Rajasthan'), ('23', 'Sikkim'), ('24', 'Tamil Nadu'), ('25', 'Telangana'), ('26', 'Tripura'), ('27', 'Uttar Pradesh'), ('28', 'Uttarakhand'), ('29', 'West Bengal')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='exceptionlistorgapplicants',
            unique_together=set([('employee_email', 'exception_type', 'program')]),
        ),
        migrations.AddField(
            model_name='programqualificationrequirements',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programqualificationrequirements_requests_created_1', to='registrations.Program'),
        ),
        migrations.AddField(
            model_name='programqualificationrequirements',
            name='qualification_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programqualificationrequirements_requests_created_2', to='registrations.QualificationCategory'),
        ),
        migrations.AddField(
            model_name='firstsemcourselist',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstsemcourselist_requests_created_1', to='registrations.Program'),
        ),
        migrations.AddField(
            model_name='degree',
            name='qualification_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='degree_requests_created_1', to='registrations.QualificationCategory'),
        ),
        migrations.AlterUniqueTogether(
            name='programqualificationrequirements',
            unique_together=set([('program', 'qualification_category')]),
        ),
    ]
