# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-10 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0014_auto_20161025_1358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationdocument',
            options={'ordering': ['-document__mandatory_document']},
        ),
        migrations.AlterModelOptions(
            name='degree',
            options={'ordering': ['degree_short_name']},
        ),
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ['-mandatory_document']},
        ),
        migrations.AlterModelOptions(
            name='programdocumentmap',
            options={'ordering': ['-mandatory_flag']},
        ),
        migrations.AddField(
            model_name='program',
            name='admit_sem_des',
            field=models.CharField(default='admit semester description', max_length=30, verbose_name='Admit Semester Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='degree',
            name='degree_long_name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='degree',
            name='degree_short_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
