# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-25 10:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0015_auto_20161110_1839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firstsemcourselist',
            options={'ordering': ['course_id'], 'verbose_name': 'Course List', 'verbose_name_plural': 'Course List'},
        ),
        migrations.AddField(
            model_name='program_fees_admission',
            name='stud_id_gen_st_num',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='student id generate start number'),
        ),
        migrations.AlterField(
            model_name='program',
            name='offer_letter_template',
            field=models.CharField(blank=True, choices=[(None, 'Choose'), ('offer_pdf/oracle.html', 'oracle'), ('offer_pdf/non-specific-sem2.html', 'Non Specific 2016 2nd Sem')], max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='program_fees_admission',
            name='fee_expiry',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 25, 10, 14, 14, 704572, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
