# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-21 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0016_auto_20161125_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateselection',
            name='app_rej_by_su_rev_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateselection',
            name='es_com',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidateselection',
            name='es_to_su_rev',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidateselection',
            name='es_to_su_rev_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateselection',
            name='hr_cont_des',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='HR Contact Designation'),
        ),
        migrations.AddField(
            model_name='candidateselection',
            name='hr_cont_email',
            field=models.EmailField(blank=True, max_length=30, null=True, verbose_name='HR Contact Email'),
        ),
        migrations.AddField(
            model_name='candidateselection',
            name='hr_cont_mob_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, verbose_name='HR Contact Mobile Number'),
        ),
        migrations.AddField(
            model_name='candidateselection',
            name='hr_cont_name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='HR Contact Name'),
        ),
        migrations.AddField(
            model_name='candidateselection',
            name='m_des',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Mentor Designation'),
        ),
        migrations.AddField(
            model_name='candidateselection',
            name='m_email',
            field=models.EmailField(blank=True, max_length=30, null=True, verbose_name='Mentor Email'),
        ),
        migrations.AddField(
            model_name='candidateselection',
            name='m_mob_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, verbose_name='Mentor Mobile Number'),
        ),
        migrations.AddField(
            model_name='candidateselection',
            name='m_name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Mentor Name'),
        ),
        migrations.AddField(
            model_name='candidateselection',
            name='new_application_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='candidateselection',
            name='new_sel_prog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidateselection_program', to='registrations.Program'),
        ),
        migrations.AddField(
            model_name='candidateselection',
            name='prior_status',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='candidateselection',
            name='prog_ch_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidateselection',
            name='su_rev_app',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidateselection',
            name='su_rev_com',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
