# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-21 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0017_auto_20161221_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='hr_cont_req',
            field=models.BooleanField(default=True, verbose_name='HR Contact Required'),
        ),
    ]
