# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-22 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0018_program_hr_cont_req'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateselection',
            name='hr_cont_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='HR Contact Email'),
        ),
        migrations.AlterField(
            model_name='candidateselection',
            name='m_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Mentor Email'),
        ),
    ]
