# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-26 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0019_auto_20161222_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcandidatementor',
            name='application',
        ),
        migrations.AddField(
            model_name='reviewer',
            name='user_role',
            field=models.CharField(blank=True, choices=[(None, 'Choose User'), ('super-reviewer', 'Super Reviewer')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='inspected_on',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='last_uploaded_on',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='verified_rejected_by',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='candidateselection',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidateselection_requests_created_5550', to='registrations.StudentCandidateApplication', unique=True),
        ),
        migrations.AlterField(
            model_name='candidateselection',
            name='bits_rejection_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidateselection_r_1', to='registrations.BitsRejectionReason'),
        ),
        migrations.AlterField(
            model_name='candidateselection',
            name='bits_selection_rejection_by',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='candidateselection',
            name='name_verified_by',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='candidateselection',
            name='verified_student_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentcandidateapplication',
            name='current_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentcandidateapplication_requests_created_7', related_query_name='%(class)s_requests_created_7s', to='registrations.Location', verbose_name='Preferred Exam Location'),
        ),
        migrations.AlterField(
            model_name='studentcandidateapplication',
            name='email_id',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentcandidateapplication',
            name='last_updated_on_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='applicationpayment',
            unique_together=set([('fee_type', 'application')]),
        ),
        migrations.DeleteModel(
            name='StudentCandidateMentor',
        ),
    ]
