# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-06 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0021_auto_20170306_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='program_fees_admission',
            name='admit_sem_des',
            field=models.CharField(blank=True, help_text='This text will show up as the semester detail in the candidate offer letter for this program.', max_length=30, null=True, verbose_name='Admit Semester Description'),
        ),
        migrations.AlterField(
            model_name='program_fees_admission',
            name='fee_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program_fees_admission',
            name='latest_fee_amount_flag',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='programlocationdetails',
            name='fee_payment_deadline_date',
            field=models.DateTimeField(help_text='This date shows up in offer acceptance page for the applicant for the program as \n                            well as on the offer letter issued to the applicant after acceptance of admission for the program.'),
        ),
        migrations.AlterField(
            model_name='programlocationdetails',
            name='lecture_start_date',
            field=models.DateTimeField(blank=True, help_text='This date shows up in  the offer letter for the program and location where the applicant \n                            will be located while studying in the program.', null=True),
        ),
        migrations.AlterField(
            model_name='programlocationdetails',
            name='orientation_date',
            field=models.DateTimeField(blank=True, help_text='This date shows up in the offer letter for the program and location where the applicant \n                            will be located while studying in the program.', null=True),
        ),
        migrations.AlterField(
            model_name='programlocationdetails',
            name='orientation_venue',
            field=models.CharField(blank=True, help_text='This location shows up in the offer letter based on the location from where the applicant will attend the program.', max_length=100, null=True),
        ),
    ]
