# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-06 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0024_auto_20170306_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='admit_sem_des',
        ),
    ]
