# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-03 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0025_remove_program_admit_sem_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateselection',
            name='dps_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data_ported_to_sdms_datetime'),
        ),
        migrations.AddField(
            model_name='candidateselection',
            name='dps_flag',
            field=models.BooleanField(default=False, verbose_name='data_ported_to_sdms_flag'),
        ),
        migrations.AlterField(
            model_name='candidateselection',
            name='verified_student_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
