# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-04 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0028_auto_20170426_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcandidateapplication',
            name='first_name',
            field=models.CharField(max_length=25, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='studentcandidateapplication',
            name='last_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='studentcandidateapplication',
            name='middle_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
