# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-22 10:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrations', '0029_auto_20170504_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchMailConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_day', models.PositiveIntegerField(verbose_name='Initial Gap')),
                ('cutoff_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Config for Automated Emailers Registered Users who are yet to Apply',
                'verbose_name_plural': 'Config for Automated Emailers Registered Users',
            },
        ),
        migrations.CreateModel(
            name='BitsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_followup_mail_sent_on', models.DateTimeField(blank=True, null=True)),
                ('mails_sent_count', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpMailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.PositiveIntegerField(default=0)),
                ('mail_type', models.CharField(max_length=45)),
                ('mail_sent_time', models.DateTimeField(auto_now_add=True)),
                ('no_of_mails_sent', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='program',
            name='application_pdf_template',
            field=models.CharField(blank=True, choices=[(None, 'Choose'), ('app_pdf/oracle-pdf.html', 'Oracle'), ('app_pdf/wipro-pdf.html', 'Wipro'), ('app_pdf/specific-pdf.html', 'Specific Program Application Template')], max_length=45, null=True),
        ),
    ]
