# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-30 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0030_auto_20170522_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdocument',
            name='inspected_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='last_uploaded_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
