# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-02 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0031_auto_20170530_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateselection',
            name='new_application_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
