# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-09 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0032_auto_20170602_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchmailconfig',
            options={},
        ),
        migrations.AddField(
            model_name='batchmailconfig',
            name='mail_type',
            field=models.CharField(choices=[(None, 'Choose Mail'), ('1', 'Config for Automated Emailers Registered Users who are yet to Apply'), ('2', 'Config for Automated Emailers to Applications who are yet to pay Application Fees')], default='1', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bitsuser',
            name='app_fee_mail_sent_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bitsuser',
            name='last_followup_app_fee_mail_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='followupmaillog',
            name='mail_type',
            field=models.CharField(choices=[('1', 'FOLLOW UP MAIL. APPLICATION NOT FILLED'), ('2', 'FOLLOW UP MAIL. APPLICATION FEE PAYMENT')], max_length=45),
        ),
    ]
