# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-31 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0034_auto_20170728_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateselection',
            name='bits_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
