# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-31 08:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0035_auto_20170731_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateselection',
            name='bits_rejection_reason',
        ),
    ]
