# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-05 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0038_auto_20170804_1232'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CandidateLogin',
        ),
        migrations.AddField(
            model_name='applicationpayment',
            name='inserted_from_gateway_file',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicationpayment',
            name='insertion_approved_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applicationpayment',
            name='insertion_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationpayment',
            name='manual_upload_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicationpayment',
            name='matched_with_payment_gateway',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicationpayment',
            name='missing_from_gateway_file',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicationpayment',
            name='tpsl_transaction',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='payment_reviewer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='user_role',
            field=models.CharField(blank=True, choices=[(None, 'Choose User'), ('super-reviewer', 'Super Reviewer'), ('payment-reviewer', 'Payment Reviewer')], max_length=20, null=True),
        ),
    ]
