# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-30 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0038_auto_20170804_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantexceptions',
            name='transfer_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicantexceptions_trans_pg', to='registrations.Program', verbose_name='Choose Transfer Program'),
        ),
        migrations.AddField(
            model_name='candidateselection',
            name='admitted_to_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidateselection_admit_pg', to='registrations.Program'),
        ),
        migrations.AlterField(
            model_name='applicantexceptions',
            name='offer_letter',
            field=models.CharField(blank=True, choices=[(None, 'Choose'), ('offer_pdf/oracle.html', 'oracle'), ('offer_pdf/non-specific-sem2.html', 'Non Specific 2016 2nd Sem'), ('offer_pdf/Specific-program-template.html', 'Specific-program template'), ('offer_pdf/wipro.html', 'Wipro Offer letter'), ('offer_pdf/wipro_sim.html', 'Wipro-SIM'), ('offer_pdf/wipro_wims.html', 'Wipro-WIMS'), ('offer_pdf/wipro_wase.html', 'Wipro-WASE')], max_length=100, null=True, verbose_name='Choose custom offer letter template, if applicable'),
        ),
        migrations.AlterField(
            model_name='program',
            name='offer_letter_template',
            field=models.CharField(blank=True, choices=[(None, 'Choose'), ('offer_pdf/oracle.html', 'oracle'), ('offer_pdf/non-specific-sem2.html', 'Non Specific 2016 2nd Sem'), ('offer_pdf/Specific-program-template.html', 'Specific-program template'), ('offer_pdf/wipro.html', 'Wipro Offer letter'), ('offer_pdf/wipro_sim.html', 'Wipro-SIM'), ('offer_pdf/wipro_wims.html', 'Wipro-WIMS'), ('offer_pdf/wipro_wase.html', 'Wipro-WASE')], max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='programlocationdetails',
            name='fee_payment_deadline_date',
            field=models.DateTimeField(help_text='This date shows up in offer acceptance page for the applicant for the program as \n\t\t\t\t\t\t\twell as on the offer letter issued to the applicant after acceptance of admission for the program.'),
        ),
        migrations.AlterField(
            model_name='programlocationdetails',
            name='lecture_start_date',
            field=models.DateTimeField(blank=True, help_text='This date shows up in  the offer letter for the program and location where the applicant \n\t\t\t\t\t\t\twill be located while studying in the program.', null=True),
        ),
        migrations.AlterField(
            model_name='programlocationdetails',
            name='orientation_date',
            field=models.DateTimeField(blank=True, help_text='This date shows up in the offer letter for the program and location where the applicant \n\t\t\t\t\t\t\twill be located while studying in the program.', null=True),
        ),
    ]
