# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-31 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import registrations.models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0039_auto_20170831_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdocument',
            name='file',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to=registrations.models.user_directory_path, verbose_name='Student File Upload'),
        ),
    ]
