# -*- coding: utf-8 -*-

# Generated by Django 1.9.5 on 2017-09-01 12:30

from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0040_auto_20170831_1314'),
        ('registrations', '0040_auto_20170824_1821'),
    ]

    operations = [
    ]
