# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-01 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0041_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantexceptions',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicantexceptions_app', to='registrations.StudentCandidateApplication'),
        ),
    ]
