# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-05 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0042_applicantexceptions_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='user_role',
            field=models.CharField(blank=True, choices=[(None, 'Choose User'), ('super-reviewer', 'Super Reviewer'), ('payment-reviewer', 'Payment Reviewer'), ('business-developer', 'Business Developer'), ('sub-reviewer', 'Sub Reviewer')], max_length=100, null=True),
        ),
    ]
