# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-06 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0043_auto_20170905_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitsuser',
            name='source_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bitsuser_pg', to='registrations.Program'),
        ),
        migrations.AddField(
            model_name='bitsuser',
            name='source_site',
            field=models.CharField(choices=[(None, 'choose site'), ('bits websites', 'BITS WEBSITES'), ('email campaign', 'EMAIL CAMPAIGN'), ('advertisement', 'ADVERTISEMENT'), ('others', 'OTHERS')], default=None, max_length=50),
        ),
    ]
