# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-08 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0044_auto_20170906_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcandidateapplication',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='studentcandidateapplication',
            name='pin_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
