# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-08 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0045_auto_20170908_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitsuser',
            name='source_site',
            field=models.CharField(blank=True, choices=[(None, 'choose site'), ('bits websites', 'BITS WEBSITES'), ('email campaign', 'EMAIL CAMPAIGN'), ('advertisement', 'ADVERTISEMENT'), ('others', 'OTHERS')], max_length=50, null=True),
        ),
    ]
