# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-18 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0040_auto_20170831_1324'),
        ('registrations', '0048_auto_20170915_1634'),
    ]

    operations = [
    ]
