# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-27 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0053_auto_20171026_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcandidateapplication',
            name='current_employment_status',
            field=models.CharField(choices=[(None, 'Choose Employment Status'), ('1', 'Employed'), ('3', 'Self Employed'), ('2', 'Unemployed'), ('4', 'Not Applicable')], max_length=20),
        ),
    ]
