# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-14 13:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0056_auto_20171122_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['serial_number_on_page']},
        ),
        migrations.AddField(
            model_name='exceptionlistorgapplicants',
            name='fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='program_fees_admission',
            name='admit_sem_cohort',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AddField(
            model_name='studentcandidateapplication',
            name='admit_sem_cohort',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='applicantexceptions',
            name='offer_letter',
            field=models.CharField(blank=True, choices=[(None, 'Choose'), ('offer_pdf/oracle.html', 'oracle'), ('offer_pdf/non-specific-sem2.html', 'Non Specific 2016 2nd Sem'), ('offer_pdf/Specific-program-template.html', 'Specific-program template'), ('offer_pdf/wipro.html', 'Wipro Offer letter'), ('offer_pdf/wipro_sim.html', 'Wipro-SIM'), ('offer_pdf/wipro_wims.html', 'Wipro-WIMS'), ('offer_pdf/wipro_wase.html', 'Wipro-WASE'), ('offer_pdf/cluster.html', 'Cluster Offer Letter'), ('offer_pdf/cluster1.html', 'Cluster Offer Letter 1'), ('offer_pdf/cluster_pg_2018.html', 'Cluster Program Offer Letter - 2018'), ('offer_pdf/bosch_man.html', 'Bosch Offer Letter Manufacturing'), ('offer_pdf/bosch_pg_man.html', 'Bosch Offer Letter PG Diploma Manufacturing'), ('offer_pdf/mtech_pom_mum_hyd.html', 'M.Tech POM Offer Letter-Mumbai-Hyd'), ('offer_pdf/mtech_pom_ahmd.html', 'M.Tech POM Offer Letter-Ahmedabad'), ('offer_pdf/embedded_sys_cluster.html', 'Embedded System Cluster Offer Letter 2017-18 Sem1'), ('offer_pdf/bosch_iti.html', 'Bosch Offer Letter-ITI Applicants'), ('offer_pdf/iot_certificate.html', 'IOT Certification Offer Letter')], max_length=100, null=True, verbose_name='Choose custom offer letter template, if applicable'),
        ),
        migrations.AlterField(
            model_name='program',
            name='offer_letter_template',
            field=models.CharField(blank=True, choices=[(None, 'Choose'), ('offer_pdf/oracle.html', 'oracle'), ('offer_pdf/non-specific-sem2.html', 'Non Specific 2016 2nd Sem'), ('offer_pdf/Specific-program-template.html', 'Specific-program template'), ('offer_pdf/wipro.html', 'Wipro Offer letter'), ('offer_pdf/wipro_sim.html', 'Wipro-SIM'), ('offer_pdf/wipro_wims.html', 'Wipro-WIMS'), ('offer_pdf/wipro_wase.html', 'Wipro-WASE'), ('offer_pdf/cluster.html', 'Cluster Offer Letter'), ('offer_pdf/cluster1.html', 'Cluster Offer Letter 1'), ('offer_pdf/cluster_pg_2018.html', 'Cluster Program Offer Letter - 2018'), ('offer_pdf/bosch_man.html', 'Bosch Offer Letter Manufacturing'), ('offer_pdf/bosch_pg_man.html', 'Bosch Offer Letter PG Diploma Manufacturing'), ('offer_pdf/mtech_pom_mum_hyd.html', 'M.Tech POM Offer Letter-Mumbai-Hyd'), ('offer_pdf/mtech_pom_ahmd.html', 'M.Tech POM Offer Letter-Ahmedabad'), ('offer_pdf/embedded_sys_cluster.html', 'Embedded System Cluster Offer Letter 2017-18 Sem1'), ('offer_pdf/bosch_iti.html', 'Bosch Offer Letter-ITI Applicants'), ('offer_pdf/iot_certificate.html', 'IOT Certification Offer Letter')], max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='studentcandidateapplication',
            name='state',
            field=models.CharField(choices=[(None, 'Choose State(India)'), ('1', 'Andhra Pradesh'), ('35', 'Andaman and Nicobar Islands'), ('2', 'Arunachal Pradesh'), ('3', 'Assam'), ('4', 'Bihar'), ('34', 'Chandigarh'), ('5', 'Chhattisgarh'), ('33', 'Dadra and Nagar Haveli'), ('32', 'Daman and Diu'), ('31', 'Delhi'), ('6', 'Goa'), ('7', 'Gujarat'), ('8', 'Haryana'), ('9', 'Himachal Pradesh'), ('10', 'Jammu and Kashmir'), ('11', 'Jharkhand'), ('12', 'Karnataka'), ('13', 'Kerala'), ('36', 'Lakshadweep'), ('14', 'Madhya Pradesh'), ('15', 'Maharashtra'), ('16', 'Manipur'), ('17', 'Meghalaya'), ('18', 'Mizoram'), ('19', 'Nagaland'), ('20', 'Odisha (Orissa)'), ('30', 'Out Side India'), ('37', 'Pondicherry'), ('21', 'Punjab'), ('22', 'Rajasthan'), ('23', 'Sikkim'), ('24', 'Tamil Nadu'), ('25', 'Telangana'), ('26', 'Tripura'), ('27', 'Uttar Pradesh'), ('28', 'Uttarakhand'), ('29', 'West Bengal')], max_length=20),
        ),
    ]
