# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-15 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0057_auto_20180314_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firstsemcourselist',
            old_name='admit_batch',
            new_name='admit_year',
        ),
        migrations.RenameField(
            model_name='program_fees_admission',
            old_name='admit_batch',
            new_name='admit_year',
        ),
        migrations.RenameField(
            model_name='studentcandidateapplication',
            old_name='admit_batch',
            new_name='admit_year',
        ),
    ]
