# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-15 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0058_auto_20180315_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcandidateapplication',
            name='admit_batch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
