# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-15 12:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0059_studentcandidateapplication_admit_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program_fees_admission',
            name='admit_sem_cohort',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
