# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-15 12:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0061_auto_20180315_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcandidateapplication',
            name='admit_sem_cohort',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
