# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-16 12:11
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0063_candidateselection_offer_letter_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceptionlistorgapplicants',
            name='fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
