# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-04-06 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0065_auto_20180323_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherFeePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('fee_type', models.CharField(choices=[(None, 'Choose Fee Type'), ('1', 'Admission Fee'), ('2', 'Application Fee'), ('3', 'REVERSAL-APPLICATION FEE'), ('4', 'REVERSAL-ADMISSION FEE')], max_length=16)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('paid_on', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.CharField(max_length=45)),
                ('payment_bank', models.CharField(max_length=45)),
                ('gateway_total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gateway_net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uploaded_on', models.DateTimeField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otherfeepayment_prog', to='registrations.Program')),
            ],
        ),
    ]
