# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-04-06 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0066_otherfeepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherfeepayment',
            name='fee_type',
            field=models.CharField(max_length=45),
        ),
    ]
