# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-04-06 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0067_auto_20180406_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherfeepayment',
            name='gateway_net_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='otherfeepayment',
            name='gateway_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='otherfeepayment',
            name='payment_bank',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='otherfeepayment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
