# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-04 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0071_auto_20180604_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programdocumentmap',
            name='mandatory_document1',
        ),
        migrations.AddField(
            model_name='programdocumentmap',
            name='deffered_submission_flag',
            field=models.BooleanField(default=False),
        ),
    ]
