# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-11 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0072_auto_20180604_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectiveCourseList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=60)),
                ('course_units', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentElectiveSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inserted_on_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_updated_on_datetime', models.DateTimeField(auto_now=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentelectiveselection_3', to='registrations.StudentCandidateApplication')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentelectiveselection_6', to='registrations.ElectiveCourseList')),
            ],
        ),
        migrations.AddField(
            model_name='firstsemcourselist',
            name='is_elective',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentelectiveselection',
            name='course_id_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentelectiveselection_4', to='registrations.FirstSemCourseList'),
        ),
        migrations.AddField(
            model_name='studentelectiveselection',
            name='course_units',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentelectiveselection_5', to='registrations.ElectiveCourseList'),
        ),
        migrations.AddField(
            model_name='studentelectiveselection',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentelectiveselection_2', to='registrations.Program'),
        ),
        migrations.AddField(
            model_name='studentelectiveselection',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentelectiveselection_1', to='registrations.CandidateSelection'),
        ),
        migrations.AddField(
            model_name='electivecourselist',
            name='course_id_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electivecourselist_2', to='registrations.FirstSemCourseList'),
        ),
        migrations.AddField(
            model_name='electivecourselist',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electivecourselist_1', to='registrations.Program'),
        ),
    ]
