# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-15 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0075_auto_20180615_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentelectiveselection',
            name='course_units',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentelectiveselection_5', to='registrations.ElectiveCourseList'),
        ),
    ]
