# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-15 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0076_auto_20180615_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationdocument',
            name='program_document_map',
        ),
    ]
