# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-15 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0077_remove_applicationdocument_program_document_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdocument',
            name='program_document_map',
            field=models.ManyToManyField(blank=True, to='registrations.ProgramDocumentMap'),
        ),
        migrations.AddField(
            model_name='programdocumentmap',
            name='application_document',
            field=models.ManyToManyField(blank=True, to='registrations.ApplicationDocument'),
        ),
    ]
