# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-15 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0078_auto_20180615_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationdocument',
            name='program_document_map',
        ),
        migrations.RemoveField(
            model_name='programdocumentmap',
            name='application_document',
        ),
    ]
