# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-21 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0082_auto_20180621_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentelectiveselection',
            old_name='course_id',
            new_name='course',
        ),
    ]
