# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-25 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0083_auto_20180621_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='is_zest_emi_enable',
            field=models.BooleanField(default=False),
        ),
    ]
