# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-07-05 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0086_auto_20180704_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZestProgramMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.TextField(verbose_name='Merchant ID')),
                ('client_secret', models.TextField(verbose_name='Merchant Password')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zestprogrammap_1', to='registrations.Program')),
            ],
        ),
    ]
