# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-07-05 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0087_zestprogrammap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zestprogrammap',
            name='program',
        ),
        migrations.AddField(
            model_name='program',
            name='zest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_zest', to='registrations.ZestProgramMap'),
        ),
        migrations.AddField(
            model_name='zestprogrammap',
            name='merchant_name',
            field=models.CharField(default='f', max_length=45),
            preserve_default=False,
        ),
    ]
