# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-07-09 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0088_auto_20180705_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electivecourselist',
            options={'verbose_name': 'Elective Courses', 'verbose_name_plural': 'Elective Courses'},
        ),
        migrations.AddField(
            model_name='otherfeepayment',
            name='application_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='otherfeepayment',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='otherfeepayment',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='otherfeepayment',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='electivecourselist',
            name='course_id_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electivecourselist_2', to='registrations.FirstSemCourseList', verbose_name='elective slot'),
        ),
    ]
