# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-10-30 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0094_auto_20181022_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantexceptions',
            name='transfer_program',
            field=models.ForeignKey(blank=True, help_text='You may have to regenerate the offer letter if the template is changed.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicantexceptions_trans_pg', to='registrations.Program', verbose_name='Choose Transfer Program'),
        ),
        migrations.AlterField(
            model_name='candidateselection',
            name='name_verified_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
