# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-01-25 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0097_auto_20181218_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcandidateapplication',
            name='teaching_mode',
            field=models.CharField(blank=True, choices=[(None, 'Choose Teaching Mode'), ('ONLINE', 'ONLINE'), ('FACE-TO-FACE', 'FACE-TO-FACE')], max_length=45, null=True),
        ),
    ]
