# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-03-12 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0099_auto_20190215_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='enable_pre_selection_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentcandidateapplication',
            name='pre_selected_flag',
            field=models.CharField(blank=True, choices=[(None, None), (True, True), (False, False)], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentcandidateapplication',
            name='pre_selected_rejected_on_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='application_pdf_template',
            field=models.CharField(blank=True, choices=[(None, 'Choose'), ('app_pdf/oracle-pdf.html', 'Oracle'), ('app_pdf/wipro-pdf.html', 'Wipro'), ('app_pdf/specific-pdf.html', 'Specific Program Application Template'), ('app_pdf/hcl_org.html', 'HCL Collaboration - BSc Program')], max_length=60, null=True),
        ),
    ]
