# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-03-22 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0100_auto_20190312_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcandidateapplication',
            name='pre_selected_flag',
            field=models.CharField(blank=True, choices=[(None, ''), ('Accepted', 'True'), ('Rejected', 'False')], max_length=10, null=True),
        ),
    ]
