# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-04-02 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0101_auto_20190322_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherfeepayment',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='otherfeepayment',
            unique_together=set([('email', 'program', 'fee_type')]),
        ),
    ]
