# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-05-02 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0104_auto_20190502_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='active_for_admission_flag',
            field=models.BooleanField(default=False),
        ),
    ]
