# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-05-17 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0107_auto_20190516_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateselection',
            name='offer_letter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
