# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-07-03 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0108_candidateselection_offer_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdocument',
            name='verified_rejected_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
