# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-08-07 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0108_auto_20190731_1231'),
        ('registrations', '0108_auto_20190724_1854'),
    ]

    operations = [
    ]
