# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-08-09 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0111_auto_20190808_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='eduvanz_location',
            field=models.ManyToManyField(blank=True, related_name='program_edu_loc', to='registrations.Location'),
        ),
        migrations.AddField(
            model_name='program',
            name='is_eduvanz_emi_enable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='program',
            name='zest_location',
            field=models.ManyToManyField(blank=True, related_name='program_zest_loc', to='registrations.Location'),
        ),
        migrations.AlterField(
            model_name='applicationpayment',
            name='fee_type',
            field=models.CharField(choices=[(None, 'Choose Fee Type'), ('1', 'Admission Fee'), ('2', 'Application Fee'), ('3', 'REVERSAL-APPLICATION FEE'), ('4', 'REVERSAL-ADMISSION FEE'), ('5', 'Zest Loan Amount'), ('6', 'Eduvanz Loan Amount')], max_length=16),
        ),
        migrations.AlterField(
            model_name='metapayment',
            name='fee_type',
            field=models.CharField(choices=[(None, 'Choose Fee Type'), ('1', 'Admission Fee'), ('2', 'Application Fee'), ('3', 'REVERSAL-APPLICATION FEE'), ('4', 'REVERSAL-ADMISSION FEE'), ('5', 'Zest Loan Amount'), ('6', 'Eduvanz Loan Amount')], max_length=16),
        ),
        migrations.AlterField(
            model_name='program_fees_admission',
            name='fee_type',
            field=models.CharField(choices=[(None, 'Choose Fee Type'), ('1', 'Admission Fee'), ('2', 'Application Fee'), ('3', 'REVERSAL-APPLICATION FEE'), ('4', 'REVERSAL-ADMISSION FEE'), ('5', 'Zest Loan Amount'), ('6', 'Eduvanz Loan Amount')], max_length=16),
        ),
    ]
