# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-08-19 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0113_auto_20190809_2013'),
        ('registrations', '0110_merge'),
    ]

    operations = [
    ]
