# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-08-20 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0114_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationpayment',
            name='fee_type',
            field=models.CharField(choices=[(None, 'Choose Fee Type'), ('1', 'Admission Fee'), ('2', 'Application Fee'), ('3', 'REVERSAL-APPLICATION FEE'), ('4', 'REVERSAL-ADMISSION FEE'), ('5', 'Zest Loan Amount'), ('6', 'Eduvanz Loan Amount')], max_length=16),
        ),
        migrations.AlterField(
            model_name='metapayment',
            name='fee_type',
            field=models.CharField(choices=[(None, 'Choose Fee Type'), ('1', 'Admission Fee'), ('2', 'Application Fee'), ('3', 'REVERSAL-APPLICATION FEE'), ('4', 'REVERSAL-ADMISSION FEE'), ('5', 'Zest Loan Amount'), ('6', 'Eduvanz Loan Amount')], max_length=16),
        ),
        migrations.AlterField(
            model_name='program_fees_admission',
            name='fee_type',
            field=models.CharField(choices=[(None, 'Choose Fee Type'), ('1', 'Admission Fee'), ('2', 'Application Fee'), ('3', 'REVERSAL-APPLICATION FEE'), ('4', 'REVERSAL-ADMISSION FEE'), ('5', 'Zest Loan Amount'), ('6', 'Eduvanz Loan Amount')], max_length=16),
        ),
    ]
