# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-10-09 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0115_auto_20190820_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcandidateapplication',
            name='alternate_email_id',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
