# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-10-14 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0116_studentcandidateapplication_alternate_email_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateselection',
            old_name='offer_letter',
            new_name='offer_letter_tmp',
        ),
    ]
