# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-10-29 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0118_candidateselection_offer_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='program_fees_admission',
            name='is_paytm_enable',
            field=models.BooleanField(default=False),
        ),
    ]
