# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-05-08 11:02
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrations', '0123_programformnotesfields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleForceAsyncTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(blank=True, choices=[(None, 'No Table choosen (might be old one)'), (b'SaleForceLeadDataLog', 'lead'), (b'SaleForceQualificationDataLog', 'qual'), (b'SaleForceWorkExperienceDataLog', 'exp'), (b'SaleForceDocumentDataLog', 'doc')], max_length=30, null=True)),
                ('job', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('sf_status', models.CharField(blank=True, max_length=20, null=True)),
                ('context', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='saleforceuserdatalog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='saleforceleaddatalog',
            name='application',
        ),
        migrations.AddField(
            model_name='saleforceleaddatalog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saleforceleaddatalog_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='programformnotesfields',
            name='notes',
            field=ckeditor.fields.RichTextField(verbose_name='Form Notes'),
        ),
        migrations.AlterField(
            model_name='saleforcedocumentdatalog',
            name='dataset',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saleforcedocumentdatalog',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saleforcedocumentdatalog_ad', to='registrations.ApplicationDocument'),
        ),
        migrations.AlterField(
            model_name='saleforceleaddatalog',
            name='dataset',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saleforcequalificationdatalog',
            name='dataset',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saleforcequalificationdatalog',
            name='qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saleforcequalificationdatalog_qual', to='registrations.StudentCandidateQualification'),
        ),
        migrations.AlterField(
            model_name='saleforceworkexperiencedatalog',
            name='dataset',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saleforceworkexperiencedatalog',
            name='work_experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saleforceworkexperiencedatalog_exp', to='registrations.StudentCandidateWorkExperience'),
        ),
        migrations.DeleteModel(
            name='SaleForceUserDataLog',
        ),
    ]
