# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-05-28 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0125_auto_20200528_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='is_ezcred_emi_enable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='applicationpayment',
            name='fee_type',
            field=models.CharField(choices=[(None, 'Choose Fee Type'), ('1', 'Admission Fee'), ('2', 'Application Fee'), ('3', 'REVERSAL-APPLICATION FEE'), ('4', 'REVERSAL-ADMISSION FEE'), ('5', 'Zest Loan Amount'), ('6', 'Eduvanz Loan Amount'), ('7', 'Ezcred Loan Amount')], max_length=16),
        ),
        migrations.AlterField(
            model_name='metapayment',
            name='fee_type',
            field=models.CharField(choices=[(None, 'Choose Fee Type'), ('1', 'Admission Fee'), ('2', 'Application Fee'), ('3', 'REVERSAL-APPLICATION FEE'), ('4', 'REVERSAL-ADMISSION FEE'), ('5', 'Zest Loan Amount'), ('6', 'Eduvanz Loan Amount'), ('7', 'Ezcred Loan Amount')], max_length=16),
        ),
        migrations.AlterField(
            model_name='program_fees_admission',
            name='fee_type',
            field=models.CharField(choices=[(None, 'Choose Fee Type'), ('1', 'Admission Fee'), ('2', 'Application Fee'), ('3', 'REVERSAL-APPLICATION FEE'), ('4', 'REVERSAL-ADMISSION FEE'), ('5', 'Zest Loan Amount'), ('6', 'Eduvanz Loan Amount'), ('7', 'Ezcred Loan Amount')], max_length=16),
        ),
    ]
