# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-07-20 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0126_auto_20200528_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherfeepayment',
            name='Zest_Program_Map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otherfeepayment_zest_adhoc', to='registrations.ZestProgramMap'),
        ),
        migrations.AddField(
            model_name='otherfeepayment',
            name='enable_ABFL_flag',
            field=models.BooleanField(default=False, verbose_name='Enable ABFL'),
        ),
        migrations.AddField(
            model_name='otherfeepayment',
            name='enable_eduvenz_flag',
            field=models.BooleanField(default=False, verbose_name='Enable Eduvanz'),
        ),
        migrations.AddField(
            model_name='otherfeepayment',
            name='enable_zest_flag',
            field=models.BooleanField(default=False, verbose_name='Enable Zest'),
        ),
    ]
