# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-08-19 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0130_auto_20200806_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaytmTransactionStatus',
            fields=[
                ('order_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_application_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('request_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=30, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(blank=True, max_length=100, null=True)),
                ('gateway_name', models.CharField(blank=True, max_length=100, null=True)),
                ('merchant_id', models.CharField(blank=True, max_length=100, null=True)),
                ('response_message', models.TextField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('resp_json', jsonfield.fields.JSONField(blank=True, null=True)),
                ('fee_type', models.CharField(choices=[(None, 'Choose Fee Type'), ('1', 'Admission Fee'), ('2', 'Application Fee'), ('3', 'REVERSAL-APPLICATION FEE'), ('4', 'REVERSAL-ADMISSION FEE'), ('5', 'Zest Loan Amount'), ('6', 'Eduvanz Loan Amount'), ('7', 'Ezcred Loan Amount')], max_length=16)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paytmtransactionstatus_requests_created_713', to='registrations.StudentCandidateApplication')),
            ],
        ),
    ]
