# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-08-24 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0131_paytmtransactionstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='metapayment',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
