# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-01-12 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0139_auto_20200923_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropelldProgramMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propelld_name', models.CharField(max_length=45, verbose_name='PROPELLD NAME')),
                ('client_id', models.TextField(verbose_name='Merchant ID')),
                ('client_secret', models.TextField(verbose_name='Merchant Password')),
            ],
        ),
        migrations.AddField(
            model_name='otherfeepayment',
            name='enable_propelld_flag',
            field=models.BooleanField(default=False, verbose_name='Enable PROPELLD'),
        ),
        migrations.AddField(
            model_name='program',
            name='is_propelld_emi_enable',
            field=models.BooleanField(default=False, verbose_name='Enable Propelld for Admission Fee Payment'),
        ),
        migrations.AlterField(
            model_name='applicationpayment',
            name='fee_type',
            field=models.CharField(choices=[(None, 'Choose Fee Type'), ('1', 'Admission Fee'), ('2', 'Application Fee'), ('3', 'REVERSAL-APPLICATION FEE'), ('4', 'REVERSAL-ADMISSION FEE'), ('5', 'Zest Loan Amount'), ('6', 'Eduvanz Loan Amount'), ('7', 'Ezcred Loan Amount'), ('8', 'Propelld Loan Amount')], max_length=16),
        ),
        migrations.AlterField(
            model_name='metapayment',
            name='fee_type',
            field=models.CharField(choices=[(None, 'Choose Fee Type'), ('1', 'Admission Fee'), ('2', 'Application Fee'), ('3', 'REVERSAL-APPLICATION FEE'), ('4', 'REVERSAL-ADMISSION FEE'), ('5', 'Zest Loan Amount'), ('6', 'Eduvanz Loan Amount'), ('7', 'Ezcred Loan Amount'), ('8', 'Propelld Loan Amount')], max_length=16),
        ),
        migrations.AlterField(
            model_name='paytmtransactionstatus',
            name='fee_type',
            field=models.CharField(choices=[(None, 'Choose Fee Type'), ('1', 'Admission Fee'), ('2', 'Application Fee'), ('3', 'REVERSAL-APPLICATION FEE'), ('4', 'REVERSAL-ADMISSION FEE'), ('5', 'Zest Loan Amount'), ('6', 'Eduvanz Loan Amount'), ('7', 'Ezcred Loan Amount'), ('8', 'Propelld Loan Amount')], max_length=16),
        ),
        migrations.AlterField(
            model_name='program',
            name='is_eduvanz_emi_enable',
            field=models.BooleanField(default=False, verbose_name='Enable Eduvanz for Admission Fee Payment'),
        ),
        migrations.AlterField(
            model_name='program',
            name='is_ezcred_emi_enable',
            field=models.BooleanField(default=False, verbose_name='Enable EzCred (ABFL) for Admission Fee Payment'),
        ),
        migrations.AlterField(
            model_name='program',
            name='is_zest_emi_enable',
            field=models.BooleanField(default=False, verbose_name='Enable Zest for Admission Fee Payment'),
        ),
        migrations.AlterField(
            model_name='program',
            name='zest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_zest', to='registrations.ZestProgramMap', verbose_name='Choose Zest EMI Plan'),
        ),
        migrations.AlterField(
            model_name='program_fees_admission',
            name='fee_type',
            field=models.CharField(choices=[(None, 'Choose Fee Type'), ('1', 'Admission Fee'), ('2', 'Application Fee'), ('3', 'REVERSAL-APPLICATION FEE'), ('4', 'REVERSAL-ADMISSION FEE'), ('5', 'Zest Loan Amount'), ('6', 'Eduvanz Loan Amount'), ('7', 'Ezcred Loan Amount'), ('8', 'Propelld Loan Amount')], max_length=16),
        ),
        migrations.AddField(
            model_name='otherfeepayment',
            name='Propelld_Program_Map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otherfeepayment_propelld_adhoc', to='registrations.PropelldProgramMap'),
        ),
        migrations.AddField(
            model_name='program',
            name='propelld',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_propelld', to='registrations.PropelldProgramMap', verbose_name='Choose Propelld EMI Plan'),
        ),
    ]
