# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-02-24 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0144_auto_20210206_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherfeepayment',
            name='propelld_course_id',
            field=models.IntegerField(blank=True, max_length=30, null=True, verbose_name='Enter Propelld Course ID'),
        ),
        migrations.AddField(
            model_name='program',
            name='propelld_course_id',
            field=models.IntegerField(blank=True, max_length=30, null=True, verbose_name='Enter Propelld Course ID'),
        ),
    ]
