# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-07-01 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0150_auto_20210621_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificAdmissionDataLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_inserted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('sent_to_sf_on', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=45)),
                ('dataset', jsonfield.fields.JSONField(blank=True, null=True)),
                ('reference_id', models.CharField(max_length=100)),
                ('response', jsonfield.fields.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpecificAdmissionSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_code', models.CharField(max_length=6)),
                ('admit_batch', models.CharField(max_length=20)),
                ('admit_sem_cohort', models.PositiveIntegerField()),
                ('application_count', models.PositiveIntegerField(blank=True, null=True)),
                ('full_submission_count', models.PositiveIntegerField(blank=True, null=True)),
                ('offered_count', models.PositiveIntegerField(blank=True, null=True)),
                ('admission_count', models.PositiveIntegerField(blank=True, null=True)),
                ('reject_count', models.PositiveIntegerField(blank=True, null=True)),
                ('last_updated_datetime', models.DateTimeField(auto_now=True)),
                ('specific_program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specificadmissionsummary_pg', to='registrations.Program')),
            ],
        ),
        migrations.AddField(
            model_name='specificadmissiondatalog',
            name='specificadmission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specificadmissiondatalog_sds', to='registrations.SpecificAdmissionSummary'),
        ),
    ]
