# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-09-23 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0153_auto_20210823_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateselection',
            name='verified_student_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
