# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-04-11 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0154_auto_20210923_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleForceAuthResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_resp', jsonfield.fields.JSONField()),
                ('status_code', models.IntegerField(max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
