# Generated by Django 3.2 on 2021-05-28 05:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import master.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ExamSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_name', models.CharField(max_length=45, unique=True)),
                ('slot_day', models.CharField(max_length=10)),
                ('slot_date', models.DateField()),
                ('slot_start_time', models.TimeField(default=datetime.time(0, 0), verbose_name='Slot Exam Start Time')),
            ],
            options={
                'unique_together': {('slot_name', 'slot_day', 'slot_date')},
            },
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='RemoteUserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('user_remote_code', models.CharField(max_length=80, unique=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='SetQpSubmissionsLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock_flag', models.BooleanField(default=False)),
                ('lock_all_submissions_flag', models.BooleanField(default=False, verbose_name='Lock all Submissions(This is disable any QP upload in the system)')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master.batch')),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master.examtype')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master.semester')),
            ],
        ),
        migrations.CreateModel(
            name='RemoteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.remoteuserrole')),
            ],
        ),
        migrations.CreateModel(
            name='QpSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20)),
                ('faculty_email_id', models.CharField(max_length=60)),
                ('course_name', models.CharField(max_length=50)),
                ('qp_path', models.FileField(blank=True, null=True, upload_to=master.models.uploaded_document_path, verbose_name='Document Path')),
                ('program_type', models.CharField(choices=[(None, 'Choose Program Type'), ('SPECIFIC', 'SPECIFIC'), ('NON-SPECIFIC', 'NON-SPECIFIC'), ('CLUSTER', 'CLUSTER'), ('CERTIFICATION', 'CERTIFICATION')], max_length=15)),
                ('first_submitted_datetime', models.DateTimeField(blank=True, null=True)),
                ('last_submitted_datetime', models.DateTimeField(blank=True, null=True)),
                ('submission_locked_flag', models.BooleanField(default=False)),
                ('last_download_datetime', models.DateTimeField(blank=True, null=True)),
                ('downloaded_by', models.CharField(blank=True, max_length=50, null=True)),
                ('active_flag', models.BooleanField(default=True)),
                ('qp_guidelines_flag', models.BooleanField(blank=True, null=True)),
                ('qp_correct_flag', models.BooleanField(blank=True, null=True)),
                ('last_reminder_email_datetime', models.DateTimeField(blank=True, null=True)),
                ('acceptance_flag', models.BooleanField(default=False)),
                ('accepted_datetime', models.DateTimeField(blank=True, null=True)),
                ('rejected_flag', models.BooleanField(default=False)),
                ('rejected_datetime', models.DateTimeField(blank=True, null=True)),
                ('rejection_comments', models.CharField(blank=True, max_length=300, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master.batch')),
                ('exam_slot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master.examslot')),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master.examtype')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master.semester')),
            ],
            options={
                'unique_together': {('semester', 'course_code', 'exam_type', 'batch')},
            },
        ),
    ]
