# Generated by Django 3.2 on 2021-06-08 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name_plural': 'Batch'},
        ),
        migrations.AlterModelOptions(
            name='examslot',
            options={'verbose_name_plural': 'Exam Slot'},
        ),
        migrations.AlterModelOptions(
            name='examtype',
            options={'verbose_name_plural': 'Exam Type'},
        ),
        migrations.AlterModelOptions(
            name='qpsubmission',
            options={'verbose_name_plural': 'QP Submissions'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'verbose_name_plural': 'Semester'},
        ),
        migrations.AlterModelOptions(
            name='setqpsubmissionslock',
            options={'verbose_name_plural': 'Set QP Submission Locks'},
        ),
    ]
