# Generated by Django 3.2 on 2021-06-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20210608_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpsubmission',
            name='active_flag',
            field=models.BooleanField(default=True, verbose_name='Exam Active Flag / QP Upload Active Flag'),
        ),
    ]
