# Generated by Django 3.2 on 2021-07-05 19:07

from django.db import migrations, models
import master.models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_auto_20210705_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpsubmission',
            name='qp_path',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=master.models.uploaded_document_path, verbose_name='Document Path'),
        ),
    ]
