# Generated by Django 3.2 on 2021-07-08 11:15

from django.db import migrations, models
import django.db.models.deletion
import master.models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_alter_qpsubmission_qp_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpsubmission',
            name='batch',
            field=models.ForeignKey(blank=True, default=master.models.get_batch_name, on_delete=django.db.models.deletion.DO_NOTHING, to='master.batch'),
        ),
    ]
