# Generated by Django 3.2 on 2021-07-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_alter_qpsubmission_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpsubmission',
            name='active_flag',
            field=models.BooleanField(default=True, help_text='To enable faculty to resubmit a question paper after acceptance or download \n                                                        by Instruction cell team, please uncheck BOTH the lock and accept flags and \n                                                        save the record', verbose_name='Exam Active Flag / QP Upload Active Flag'),
        ),
    ]
