# Generated by Django 3.2 on 2021-08-09 17:45

from django.db import migrations, models
import django.db.models.deletion
import master.models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_alter_qpsubmission_active_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpsubmission',
            name='batch',
            field=models.ForeignKey(blank=True, default=master.models.get_batch_name, on_delete=django.db.models.deletion.CASCADE, to='master.batch'),
        ),
        migrations.AlterField(
            model_name='qpsubmission',
            name='exam_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.examslot'),
        ),
        migrations.AlterField(
            model_name='qpsubmission',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.examtype'),
        ),
        migrations.AlterField(
            model_name='qpsubmission',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.semester'),
        ),
        migrations.AlterField(
            model_name='setqpsubmissionslock',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.batch'),
        ),
        migrations.AlterField(
            model_name='setqpsubmissionslock',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.examtype'),
        ),
        migrations.AlterField(
            model_name='setqpsubmissionslock',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.semester'),
        ),
    ]
