# Generated by Django 3.2 on 2021-12-15 07:38

from django.db import migrations, models
import master.models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_auto_20210809_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpsubmission',
            name='alternate_qp_path',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=master.models.alternate_qp_document_path, verbose_name='Alternate Document Path'),
        ),
        migrations.AddField(
            model_name='qpsubmission',
            name='alternate_qp_submit_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qpsubmission',
            name='coordinator_email_id_1',
            field=models.EmailField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='qpsubmission',
            name='coordinator_email_id_2',
            field=models.EmailField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='qpsubmission',
            name='email_access_id_1',
            field=models.EmailField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='qpsubmission',
            name='email_access_id_2',
            field=models.EmailField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='qpsubmission',
            name='submitted_by_faculty',
            field=models.EmailField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='qpsubmission',
            name='faculty_email_id',
            field=models.EmailField(max_length=60),
        ),
        migrations.CreateModel(
            name='StaffUserAccessList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.EmailField(max_length=60)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('created_by_user_id', models.EmailField(max_length=60)),
                ('coordinator_flag', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Staff user access list',
                'unique_together': {('user_id',)},
            },
        ),
    ]
