# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-05 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrations', '0039_auto_20170806_0234'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualPaymentDataUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=45, unique=True)),
                ('payment_type', models.CharField(choices=[(None, 'Choose Fee Type'), ('1', 'Admission Fee'), ('2', 'Application Fee')], max_length=20)),
                ('payment_date', models.DateTimeField()),
                ('payment_amount', models.FloatField()),
                ('payment_mode', models.CharField(blank=True, max_length=30, null=True)),
                ('uploaded_by', models.CharField(max_length=50)),
                ('uploaded_on_date', models.DateTimeField(auto_now_add=True)),
                ('payment_reversal_flag', models.BooleanField()),
                ('status', models.CharField(choices=[(None, 'Choose'), ('1', 'Uploaded. Pending Review'), ('2', 'Fee Mismatch'), ('3', 'Approved'), ('4', 'Rejected')], max_length=30)),
                ('accepted_rejected_datetime', models.DateTimeField(blank=True, null=True)),
                ('accepted_rejected_by', models.CharField(blank=True, max_length=50, null=True)),
                ('upload_filename', models.CharField(max_length=100)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manualpaymentdataupload_app', to='registrations.StudentCandidateApplication')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentGatewayRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpsl_transaction_id', models.CharField(max_length=20, unique=True)),
                ('bank_id', models.PositiveIntegerField()),
                ('bank_name', models.CharField(max_length=50)),
                ('sm_transaction_id', models.CharField(max_length=45, unique=True)),
                ('bank_transaction_id', models.CharField(max_length=45, unique=True)),
                ('total_amount', models.FloatField()),
                ('charges', models.FloatField()),
                ('service_tax', models.FloatField()),
                ('net_amount', models.FloatField()),
                ('transaction_date', models.DateTimeField()),
                ('src_itc_user_id', models.CharField(max_length=50)),
                ('src_itc_user_name', models.CharField(max_length=50)),
                ('src_itc_mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('uploaded_by', models.CharField(max_length=50)),
                ('uploaded_on_datetime', models.DateTimeField(auto_now_add=True)),
                ('payment_file_name', models.CharField(max_length=50)),
                ('payment_report_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[(None, 'Choose'), ('1', 'Uploaded. Pending Review'), ('2', 'Matched and Approved'), ('3', 'Fee Mismatch'), ('4', 'Approved. Transferred to Application Center'), ('5', 'Rejected')], max_length=30)),
                ('missing_in_application_center', models.BooleanField(default=False)),
                ('accepted_rejected_datetime', models.DateTimeField(blank=True, null=True)),
                ('accepted_rejected_by', models.CharField(blank=True, max_length=50, null=True)),
                ('src_itc_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentgatewayrecord_app', to='registrations.StudentCandidateApplication')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='paymentgatewayrecord',
            unique_together=set([('src_itc_application', 'tpsl_transaction_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='manualpaymentdataupload',
            unique_together=set([('application', 'payment_type')]),
        ),
    ]
