# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-24 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_reviewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualpaymentdataupload',
            name='payment_type',
            field=models.CharField(choices=[(None, 'Choose Fee Type'), ('1', 'Admission Fee'), ('2', 'Application Fee'), ('3', 'REVERSAL-APPLICATION FEE'), ('4', 'REVERSAL-ADMISSION FEE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentgatewayrecord',
            name='bank_transaction_id',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='paymentgatewayrecord',
            name='sm_transaction_id',
            field=models.CharField(max_length=45),
        ),
    ]
