# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-29 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_reviewer', '0002_auto_20170824_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgatewayrecord',
            name='tpsl_transaction_id',
            field=models.CharField(max_length=20),
        ),
    ]
