# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-11-22 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_reviewer', '0003_auto_20170829_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualpaymentdataupload',
            name='status',
            field=models.CharField(choices=[(None, 'Choose'), ('1', 'Uploaded. Pending Review'), ('2', 'Fee Mismatch'), ('3', 'Approved'), ('4', 'Rejected'), ('5', 'Double Payment. Rejected')], max_length=30),
        ),
        migrations.AlterField(
            model_name='paymentgatewayrecord',
            name='status',
            field=models.CharField(choices=[(None, 'Choose'), ('1', 'Uploaded. Pending Review'), ('2', 'Matched and Approved'), ('3', 'Fee Mismatch'), ('4', 'Approved. Transferred to Application Center'), ('5', 'Rejected'), ('6', 'Double Payment. Rejected')], max_length=30),
        ),
    ]
