# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-25 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_reviewer', '0004_auto_20171122_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualpaymentdataupload',
            name='payment_type',
            field=models.CharField(choices=[(None, 'Choose Fee Type'), ('1', 'Admission Fee'), ('2', 'Application Fee'), ('3', 'REVERSAL-APPLICATION FEE'), ('4', 'REVERSAL-ADMISSION FEE'), ('5', 'Zest Loan Amount')], max_length=20),
        ),
    ]
