# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-08-09 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_reviewer', '0005_auto_20180625_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualpaymentdataupload',
            name='payment_type',
            field=models.CharField(choices=[(None, 'Choose Fee Type'), ('1', 'Admission Fee'), ('2', 'Application Fee'), ('3', 'REVERSAL-APPLICATION FEE'), ('4', 'REVERSAL-ADMISSION FEE'), ('5', 'Zest Loan Amount'), ('6', 'Eduvanz Loan Amount')], max_length=20),
        ),
    ]
