# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-03 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits_admin', '0003_applicantexceptionsarchived'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionListOrgApplicantsArchived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_email', models.EmailField(db_index=True, max_length=50)),
                ('exception_type', models.CharField(blank=True, max_length=50, null=True)),
                ('org', models.CharField(blank=True, max_length=50, null=True)),
                ('program', models.CharField(blank=True, max_length=50, null=True)),
                ('employee_id', models.CharField(max_length=15)),
                ('employee_name', models.CharField(max_length=50)),
            ],
        ),
    ]
