# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-05 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits_admin', '0004_exceptionlistorgapplicantsarchived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceptionlistorgapplicantsarchived',
            name='employee_email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='exceptionlistorgapplicantsarchived',
            name='employee_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='exceptionlistorgapplicantsarchived',
            name='employee_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
