# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-11 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0047_auto_20170908_2000'),
        ('bits_admin', '0005_auto_20170905_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on_datetime', models.DateTimeField(auto_now_add=True)),
                ('api_request', jsonfield.fields.JSONField(blank=True, null=True)),
                ('api_response', jsonfield.fields.JSONField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.StudentCandidateApplication')),
            ],
        ),
    ]
