# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-11 07:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bits_admin', '0006_metapayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on_datetime', models.DateTimeField(auto_now_add=True)),
                ('api_request', jsonfield.fields.JSONField(blank=True, null=True)),
                ('api_response', jsonfield.fields.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='metapayment',
            name='application',
        ),
        migrations.DeleteModel(
            name='MetaPayment',
        ),
    ]
