# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-12 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits_admin', '0007_auto_20170911_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcandidateapplicationarchived',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentcandidateapplicationarchived',
            name='pin_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
