# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-12 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('bits_admin', '0008_auto_20170912_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateselectionarchived',
            name='acad_contact_person',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidateselectionarchived',
            name='acad_contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='candidateselectionarchived',
            name='adm_fees',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateselectionarchived',
            name='admin_contact_person',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidateselectionarchived',
            name='admin_contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='candidateselectionarchived',
            name='admitted_to_program',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidateselectionarchived',
            name='doc_resubmission_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateselectionarchived',
            name='fee_payment_deadline_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateselectionarchived',
            name='lecture_start_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateselectionarchived',
            name='lecture_venue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidateselectionarchived',
            name='offer_letter_generated_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidateselectionarchived',
            name='offer_letter_regenerated_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateselectionarchived',
            name='orientation_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateselectionarchived',
            name='orientation_venue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
