# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-15 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits_admin', '0011_auto_20170912_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdocumentarchived',
            name='document',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applicationdocumentarchived',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applicationdocumentarchived',
            name='verified_rejected_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
