# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-13 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits_admin', '0012_auto_20170915_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateselectionarchived',
            name='old_student_id',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
