# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-15 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bits_admin', '0013_candidateselectionarchived_old_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcandidateapplicationarchived',
            old_name='admit_batch',
            new_name='admit_year',
        ),
    ]
