# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-23 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits_admin', '0016_candidateselectionarchived_offer_letter_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceptionlistorgapplicantsarchived',
            name='fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
