# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-06-01 06:22
from __future__ import unicode_literals

import bits_admin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits_admin', '0017_exceptionlistorgapplicantsarchived_fee_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdocumentarchived',
            name='file',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to=bits_admin.models.user_directory_path),
        ),
    ]
