# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-09-18 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits_admin', '0019_zestemitransactionarchived'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentElectiveSelectionArchived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.PositiveIntegerField()),
                ('student_id', models.CharField(blank=True, max_length=11, null=True)),
                ('program', models.CharField(blank=True, max_length=50, null=True)),
                ('application', models.CharField(blank=True, max_length=20, null=True)),
                ('course_id_slot', models.CharField(blank=True, max_length=20, null=True)),
                ('course_units', models.PositiveIntegerField(blank=True, null=True)),
                ('course', models.CharField(blank=True, max_length=20, null=True)),
                ('inserted_on_datetime', models.DateTimeField()),
                ('last_updated_on_datetime', models.DateTimeField()),
                ('is_locked', models.BooleanField(default=False)),
            ],
        ),
    ]
