# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-10-30 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits_admin', '0020_studentelectiveselectionarchived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateselectionarchived',
            name='name_verified_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
