# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-11-01 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('bits_admin', '0021_auto_20181030_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdhocMetaZestArchived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.PositiveIntegerField()),
                ('email', models.CharField(max_length=50)),
                ('errors', jsonfield.fields.JSONField(blank=True, null=True)),
                ('created_on_datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AdhocZestEmiTransactionArchived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.PositiveIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('order_id', models.TextField(blank=True, null=True)),
                ('customer_id', models.TextField(blank=True, null=True)),
                ('requested_on', models.DateTimeField(blank=True, null=True)),
                ('is_application_complete', models.BooleanField()),
                ('approved_or_rejected_on', models.DateTimeField(blank=True, null=True)),
                ('is_approved', models.BooleanField()),
                ('is_terms_and_condition_accepted', models.BooleanField()),
                ('req_json_data', jsonfield.fields.JSONField(blank=True, null=True)),
                ('amount_requested', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManualPaymentDataUploadArchived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.PositiveIntegerField()),
                ('application', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_id', models.CharField(max_length=45, unique=True)),
                ('payment_type', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_date', models.DateTimeField()),
                ('payment_amount', models.FloatField()),
                ('payment_mode', models.CharField(blank=True, max_length=30, null=True)),
                ('uploaded_by', models.CharField(max_length=50)),
                ('uploaded_on_date', models.DateTimeField()),
                ('payment_reversal_flag', models.BooleanField()),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('accepted_rejected_datetime', models.DateTimeField(blank=True, null=True)),
                ('accepted_rejected_by', models.CharField(blank=True, max_length=50, null=True)),
                ('upload_filename', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MetaZestArchived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.PositiveIntegerField()),
                ('user', models.CharField(blank=True, max_length=20, null=True)),
                ('errors', jsonfield.fields.JSONField(blank=True, null=True)),
                ('created_on_datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentGatewayRecordArchived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.PositiveIntegerField()),
                ('src_itc_application', models.CharField(blank=True, max_length=20, null=True)),
                ('tpsl_transaction_id', models.CharField(max_length=20)),
                ('bank_id', models.PositiveIntegerField()),
                ('bank_name', models.CharField(max_length=50)),
                ('sm_transaction_id', models.CharField(max_length=45)),
                ('bank_transaction_id', models.CharField(max_length=45)),
                ('total_amount', models.FloatField()),
                ('charges', models.FloatField()),
                ('service_tax', models.FloatField()),
                ('net_amount', models.FloatField()),
                ('transaction_date', models.DateTimeField()),
                ('src_itc_user_id', models.CharField(max_length=50)),
                ('src_itc_user_name', models.CharField(max_length=50)),
                ('src_itc_mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('uploaded_by', models.CharField(max_length=50)),
                ('uploaded_on_datetime', models.DateTimeField()),
                ('payment_file_name', models.CharField(max_length=50)),
                ('payment_report_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('missing_in_application_center', models.BooleanField()),
                ('accepted_rejected_datetime', models.DateTimeField(blank=True, null=True)),
                ('accepted_rejected_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SemMetaZestArchived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.PositiveIntegerField()),
                ('student_id', models.CharField(max_length=50)),
                ('errors', jsonfield.fields.JSONField(blank=True, null=True)),
                ('created_on_datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SemZestEmiTransactionArchived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.PositiveIntegerField()),
                ('student_id', models.CharField(blank=True, max_length=50, null=True)),
                ('order_id', models.TextField(blank=True, null=True)),
                ('customer_id', models.TextField(blank=True, null=True)),
                ('requested_on', models.DateTimeField(blank=True, null=True)),
                ('is_application_complete', models.BooleanField()),
                ('approved_or_rejected_on', models.DateTimeField(blank=True, null=True)),
                ('is_approved', models.BooleanField()),
                ('is_terms_and_condition_accepted', models.BooleanField()),
                ('req_json_data', jsonfield.fields.JSONField(blank=True, null=True)),
                ('amount_requested', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCandidateApplicationSpecificArchived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.PositiveIntegerField()),
                ('application', models.CharField(blank=True, max_length=20, null=True)),
                ('collaborating_organization', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
