# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-11-05 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits_admin', '0022_adhocmetazestarchived_adhoczestemitransactionarchived_manualpaymentdatauploadarchived_metazestarchiv'),
    ]

    operations = [
        migrations.AddField(
            model_name='zestemitransactionarchived',
            name='cancelled_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zestemitransactionarchived',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
