# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-12-26 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits_admin', '0023_auto_20181105_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcandidateapplicationarchived',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
