# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-02-15 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits_admin', '0024_auto_20181226_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcandidatequalificationarchived',
            name='degree',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
