# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-04-09 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bits_admin', '0026_auto_20190409_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcandidateapplicationarchived',
            old_name='program',
            new_name='program_code',
        ),
    ]
