# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-04-09 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bits_admin', '0027_auto_20190409_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcandidateapplicationarchived',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentcandidateapplicationarchived_requests_created_6', to='bits_admin.ProgramArchived'),
        ),
    ]
