# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-04-09 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bits_admin', '0028_studentcandidateapplicationarchived_program'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programarchived',
            options={},
        ),
        migrations.RemoveField(
            model_name='programarchived',
            name='active_for_applicaton_flag',
        ),
        migrations.RemoveField(
            model_name='programarchived',
            name='alternative_program_code',
        ),
        migrations.RemoveField(
            model_name='programarchived',
            name='application_pdf_template',
        ),
        migrations.RemoveField(
            model_name='programarchived',
            name='available_in_cities',
        ),
        migrations.RemoveField(
            model_name='programarchived',
            name='collaborating_organization',
        ),
        migrations.RemoveField(
            model_name='programarchived',
            name='document_upload_page_path',
        ),
        migrations.RemoveField(
            model_name='programarchived',
            name='enable_pre_selection_flag',
        ),
        migrations.RemoveField(
            model_name='programarchived',
            name='hr_cont_req',
        ),
        migrations.RemoveField(
            model_name='programarchived',
            name='is_zest_emi_enable',
        ),
        migrations.RemoveField(
            model_name='programarchived',
            name='mentor_id_req',
        ),
        migrations.RemoveField(
            model_name='programarchived',
            name='min_work_exp_in_months',
        ),
        migrations.RemoveField(
            model_name='programarchived',
            name='offer_letter_template',
        ),
        migrations.RemoveField(
            model_name='programarchived',
            name='org_logo_image',
        ),
        migrations.RemoveField(
            model_name='programarchived',
            name='serial_number_on_page',
        ),
        migrations.RemoveField(
            model_name='programarchived',
            name='show_on_page_flag',
        ),
        migrations.RemoveField(
            model_name='programarchived',
            name='show_to_fee_wvr_appl_flag',
        ),
        migrations.RemoveField(
            model_name='programarchived',
            name='work_exp_check_req',
        ),
        migrations.RemoveField(
            model_name='programarchived',
            name='zest',
        ),
        migrations.DeleteModel(
            name='ZestProgramMapArchived',
        ),
    ]
