# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-04-09 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bits_admin', '0029_auto_20190409_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationdocumentarchived',
            old_name='application',
            new_name='application_pk',
        ),
        migrations.RenameField(
            model_name='applicationpaymentarchived',
            old_name='application',
            new_name='application_pk',
        ),
        migrations.RenameField(
            model_name='candidateselectionarchived',
            old_name='application',
            new_name='application_pk',
        ),
        migrations.RenameField(
            model_name='studentcandidateapplicationspecificarchived',
            old_name='application',
            new_name='application_pk',
        ),
        migrations.RenameField(
            model_name='studentcandidatequalificationarchived',
            old_name='application',
            new_name='application_pk',
        ),
        migrations.RenameField(
            model_name='studentcandidateworkexperiencearchived',
            old_name='application',
            new_name='application_pk',
        ),
        migrations.RenameField(
            model_name='studentelectiveselectionarchived',
            old_name='application',
            new_name='application_pk',
        ),
        migrations.RenameField(
            model_name='zestemitransactionarchived',
            old_name='application',
            new_name='application_pk',
        ),
    ]
