# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-04-09 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bits_admin', '0030_auto_20190409_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdocumentarchived',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicationdocumentarchived_5', to='bits_admin.StudentCandidateApplicationArchived'),
        ),
        migrations.AddField(
            model_name='applicationpaymentarchived',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicationpaymentarchived_2', to='bits_admin.StudentCandidateApplicationArchived'),
        ),
        migrations.AddField(
            model_name='candidateselectionarchived',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidateselectionarchived_1', to='bits_admin.StudentCandidateApplicationArchived'),
        ),
        migrations.AddField(
            model_name='studentcandidateapplicationspecificarchived',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentcandidateapplicationspecificarchived_8', to='bits_admin.StudentCandidateApplicationArchived'),
        ),
        migrations.AddField(
            model_name='studentcandidatequalificationarchived',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentcandidatequalificationarchived_4', to='bits_admin.StudentCandidateApplicationArchived'),
        ),
        migrations.AddField(
            model_name='studentcandidateworkexperiencearchived',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentcandidateworkexperiencearchived_3', to='bits_admin.StudentCandidateApplicationArchived'),
        ),
        migrations.AddField(
            model_name='studentelectiveselectionarchived',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentelectiveselectionarchived_7', to='bits_admin.StudentCandidateApplicationArchived'),
        ),
        migrations.AddField(
            model_name='zestemitransactionarchived',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zestemitransactionarchived_6', to='bits_admin.StudentCandidateApplicationArchived'),
        ),
    ]
