# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-04-12 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits_admin', '0031_auto_20190409_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcandidateapplicationarchived',
            name='pre_selected_flag',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentcandidateapplicationarchived',
            name='pre_selected_rejected_on_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcandidateapplicationarchived',
            name='teaching_mode',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
