# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-04-12 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bits_admin', '0032_auto_20190412_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manualpaymentdatauploadarchived',
            old_name='application',
            new_name='application_pk',
        ),
        migrations.RenameField(
            model_name='paymentgatewayrecordarchived',
            old_name='src_itc_application',
            new_name='src_itc_application_pk',
        ),
    ]
