# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-04-12 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits_admin', '0033_auto_20190412_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualpaymentdatauploadarchived',
            name='application',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paymentgatewayrecordarchived',
            name='src_itc_application',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
