# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-04-25 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bits_admin', '0035_degreearchived'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceptionlistorgapplicantsarchived',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exceptionlistorgapplicantsarchived_5', to='bits_admin.StudentCandidateApplicationArchived'),
        ),
    ]
