# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-04-26 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bits_admin', '0037_auto_20190426_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcandidatequalificationarchived',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentcandidatequalificationarchived_1', to='bits_admin.DegreeArchived'),
        ),
    ]
