# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-04-26 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits_admin', '0038_studentcandidatequalificationarchived_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcandidatequalificationarchived',
            name='discipline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentcandidatequalificationarchived',
            name='other_degree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentcandidatequalificationarchived',
            name='other_discipline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
