# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-05-06 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bits_admin', '0039_auto_20190426_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualpaymentdatauploadarchived',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manualpaymentdatauploadarchived_8', to='bits_admin.StudentCandidateApplicationArchived'),
        ),
        migrations.AlterField(
            model_name='paymentgatewayrecordarchived',
            name='src_itc_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paymentgatewayrecordarchived_8', to='bits_admin.StudentCandidateApplicationArchived'),
        ),
    ]
