# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-05-08 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits_admin', '0040_auto_20190506_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='programarchived',
            name='hr_cont_req',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='programarchived',
            name='mentor_id_req',
            field=models.BooleanField(default=True),
        ),
    ]
