# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-05-09 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits_admin', '0041_auto_20190508_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualpaymentdatauploadarchived',
            name='payment_id',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
