# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-05-17 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits_admin', '0043_programarchived_offer_letter_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateselectionarchived',
            name='offer_letter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
