# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-08-27 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bits_admin', '0044_candidateselectionarchived_offer_letter'),
    ]

    operations = [
        migrations.CreateModel(
            name='EduvanzApplicationArchived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.PositiveIntegerField()),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_terms_and_condition_accepted', models.BooleanField(default=False)),
                ('amount_requested', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status_code', models.CharField(blank=True, max_length=25, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('approved_or_rejected_on', models.DateTimeField(blank=True, null=True)),
                ('lead_id', models.CharField(blank=True, max_length=25, null=True)),
                ('callback_meta', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='studentcandidateapplicationarchived',
            name='programming_flag',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='eduvanzapplicationarchived',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eduvanzapplicationarchived_9', to='bits_admin.StudentCandidateApplicationArchived'),
        ),
    ]
