# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-09-27 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0115_auto_20190820_1325'),
        ('bits_admin', '0046_auto_20190828_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='degreearchived',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='degreearchived_1', to='registrations.Degree'),
        ),
        migrations.AddField(
            model_name='programarchived',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programarchived_1', to='registrations.Program'),
        ),
        migrations.AddField(
            model_name='studentcandidateapplicationarchived',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studentcandidateapplicationarchived_1', to='registrations.StudentCandidateApplication'),
        ),
        migrations.AddField(
            model_name='studentcandidateapplicationarchived',
            name='trial_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
