# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-09-27 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits_admin', '0047_auto_20190927_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhocmetaemiarchived',
            name='run',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='adhoczestemitransactionarchived',
            name='run',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='applicantexceptionsarchived',
            name='run',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='applicationdocumentarchived',
            name='run',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='applicationpaymentarchived',
            name='run',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='archiveaudittable',
            name='run',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='candidateloginarchived',
            name='run',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='candidateselectionarchived',
            name='run',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='eduvanzapplicationarchived',
            name='run',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exceptionlistorgapplicantsarchived',
            name='run',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='manualpaymentdatauploadarchived',
            name='run',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='metazestarchived',
            name='run',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paymentgatewayrecordarchived',
            name='run',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='semmetazestarchived',
            name='run',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='semzestemitransactionarchived',
            name='run',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentcandidateapplicationarchived',
            name='run',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentcandidateapplicationspecificarchived',
            name='run',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentcandidatequalificationarchived',
            name='run',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentcandidateworkexperiencearchived',
            name='run',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentelectiveselectionarchived',
            name='run',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='zestemitransactionarchived',
            name='run',
            field=models.IntegerField(),
        ),
    ]
