# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-10-14 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bits_admin', '0048_auto_20190927_2119'),
        ('bits_admin', '0047_studentcandidateapplicationarchived_alternate_email_id'),
    ]

    operations = [
    ]
