# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-10-14 11:09
from __future__ import unicode_literals

import bits_admin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits_admin', '0050_auto_20191014_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateselectionarchived',
            name='offer_letter',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to=bits_admin.models.user_directory_path),
        ),
    ]
