# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-09-16 06:35
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bits_admin', '0052_auto_20200707_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='zestemitransactionarchived',
            name='callback_meta',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
