# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-09-30 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bits_admin', '0053_zestemitransactionarchived_callback_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleForceLogCleanup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logdel_start_datetime', models.DateTimeField(blank=True, null=True)),
                ('logdel_end_datetime', models.DateTimeField(blank=True, null=True)),
                ('sf_lead_rows_deleted', models.PositiveIntegerField()),
                ('sf_document_rows_deleted', models.PositiveIntegerField()),
                ('sf_qualification_rows_deleted', models.PositiveIntegerField()),
                ('sf_workexp_rows_deleted', models.PositiveIntegerField()),
            ],
        ),
    ]
